/-
Copyright (c) 2025 exchangeability contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: exchangeability contributors
-/
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.InnerProductSpace.Projection.Basic
import Exchangeability.Ergodic.KoopmanMeanErgodic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondexpL2

/-!
# Shift-invariant σ-algebra and conditional expectation

This file defines the shift-invariant σ-algebra on path space and establishes
the fundamental connection between:
- The fixed-point subspace of the Koopman operator
- The L² space with respect to the shift-invariant σ-algebra
- The conditional expectation onto the shift-invariant σ-algebra

## Main definitions

* `isShiftInvariant`: Predicate for sets that are invariant under the shift map.
* `shiftInvariantSigma`: The σ-algebra of shift-invariant sets.
* `fixedSubspace`: The subspace of L² functions fixed by the Koopman operator.

## Main results

* `mem_shiftInvariantSigma_iff`: Characterization of membership in the invariant σ-algebra.
* `fixedSpace_eq_invMeasurable`: Functions fixed by Koopman are exactly those
  measurable with respect to the shift-invariant σ-algebra.
* `proj_eq_condexp`: The orthogonal projection onto the fixed-point subspace equals
  the conditional expectation onto the shift-invariant σ-algebra.

## References

* Olav Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*,
  Springer, Chapter 1 (pages 26-27). The shift-invariant σ-algebra is denoted
  𝓘_ξ in Kallenberg.

-/

noncomputable section

open scoped Classical

namespace Exchangeability.DeFinetti

open MeasureTheory Filter Topology
open Exchangeability.Ergodic

variable {α : Type*} [MeasurableSpace α]

/-- A set is shift-invariant if it is measurable and equals its preimage under shift. -/
def isShiftInvariant (s : Set (Ω[α])) : Prop :=
  MeasurableSet s ∧ shift ⁻¹' s = s

lemma isShiftInvariant_iff (s : Set (Ω[α])) :
    isShiftInvariant s ↔ MeasurableSet s ∧ ∀ ω, shift ω ∈ s ↔ ω ∈ s := by
  constructor
  · intro ⟨hm, heq⟩
    exact ⟨hm, fun ω => by rw [← Set.mem_preimage, heq]⟩
  · intro ⟨hm, hiff⟩
    refine ⟨hm, Set.ext fun ω => ?_⟩
    simp [hiff]

/-- The shift-invariant σ-algebra: the collection of shift-invariant sets.

For now we define this axiomatically; a full construction would use the σ-algebra
generated by shift-invariant sets or the comap construction.
-/
def shiftInvariantSigma : MeasurableSpace (Ω[α]) where
  MeasurableSet' := fun s => isShiftInvariant (α := α) s
  measurableSet_empty := by
    refine ⟨MeasurableSet.empty, ?_⟩
    simp
  measurableSet_compl := by
    intro s hs
    obtain ⟨hs_meas, hs_eq⟩ := hs
    refine ⟨hs_meas.compl, ?_⟩
    simp [Set.preimage_compl, hs_eq]
  measurableSet_iUnion := by
    intro f hf
    refine ⟨MeasurableSet.iUnion fun n => (hf n).left, ?_⟩
    simp only [Set.preimage_iUnion]
    ext ω
    simp only [Set.mem_iUnion, Set.mem_preimage]
    constructor
    · intro ⟨i, hi⟩
      use i
      -- hi : shift ω ∈ f i
      -- By (hf i), f i is shift-invariant: shift ω ∈ f i ↔ ω ∈ f i
      have := (isShiftInvariant_iff (f i)).1 (hf i)
      exact (this.2 ω).1 hi
    · intro ⟨i, hi⟩
      use i
      -- hi : ω ∈ f i
      -- By (hf i), f i is shift-invariant: shift ω ∈ f i ↔ ω ∈ f i
      have := (isShiftInvariant_iff (f i)).1 (hf i)
      exact (this.2 ω).2 hi

lemma shiftInvariantSigma_le :
    shiftInvariantSigma ≤ (inferInstance : MeasurableSpace (Ω[α])) := by
  intro s hs
  exact (hs : isShiftInvariant (α := α) s).1

lemma mem_shiftInvariantSigma_iff (s : Set (Ω[α])) :
    @MeasurableSet _ shiftInvariantSigma s ↔ isShiftInvariant (α := α) s :=
  Iff.rfl

/-- Shift-invariant measurability forces pointwise invariance under the shift map. -/
lemma shiftInvariantSigma_measurable_shift_eq
    (g : Ω[α] → ℝ)
    (hg : Measurable[shiftInvariantSigma] g) :
    (fun ω => g (shift ω)) = g := by
  classical
  ext ω
  by_contra hneq
  have hlt_or := lt_or_gt_of_ne hneq
  cases hlt_or with
  | inl hlt =>
      -- Case `g (shift ω) < g ω`
      obtain ⟨q, hltq, hqω⟩ := exists_rat_btwn hlt
      have hmeas : MeasurableSet (Set.Iio (q : ℝ)) :=
        (isOpen_Iio : IsOpen (Set.Iio (q : ℝ))).measurableSet
      have hset_eq := (hg hmeas).2
      have h_shift_mem : shift ω ∈ g ⁻¹' Set.Iio (q : ℝ) := by
        simpa [Set.mem_preimage] using hltq
      have h_pre : ω ∈ shift ⁻¹' (g ⁻¹' Set.Iio (q : ℝ)) := by
        simpa [Set.mem_preimage] using h_shift_mem
      have h_mem : ω ∈ g ⁻¹' Set.Iio (q : ℝ) := by
        simpa [hset_eq] using h_pre
      have : g ω < (q : ℝ) := by
        simpa [Set.mem_preimage] using h_mem
      have : g ω < g ω := lt_trans this hqω
      exact lt_irrefl _ this
  | inr hgt =>
      -- Case `g ω < g (shift ω)`
      obtain ⟨q, hωq, hq_lt⟩ := exists_rat_btwn hgt
      have hmeas : MeasurableSet (Set.Ioi (q : ℝ)) :=
        (isOpen_Ioi : IsOpen (Set.Ioi (q : ℝ))).measurableSet
      have hset_eq := (hg hmeas).2
      have h_shift_mem : shift ω ∈ g ⁻¹' Set.Ioi (q : ℝ) := by
        simpa [Set.mem_preimage] using hq_lt
      have h_pre : ω ∈ shift ⁻¹' (g ⁻¹' Set.Ioi (q : ℝ)) := by
        simpa [Set.mem_preimage] using h_shift_mem
      have h_mem : ω ∈ g ⁻¹' Set.Ioi (q : ℝ) := by
        simpa [hset_eq] using h_pre
      have : (q : ℝ) < g ω := by
        simpa [Set.mem_preimage] using h_mem
      have : g ω < g ω := lt_trans hωq this
      exact lt_irrefl _ this

/-- **Auxiliary goal**: construct an invariant representative.

Once `g : Ω[α] → ℝ` is strongly measurable and agrees a.e. with its shift, we expect to
modify it on a null set so that it becomes literally invariant under `shift` while remaining
measurable with respect to `shiftInvariantSigma`.  Filling in this lemma (or a closely related
variant) will let us finish `aestronglyMeasurable_shiftInvariant_of_koopman`. -/
lemma exists_shiftInvariantRepresentative
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    (g : Ω[α] → ℝ)
    (hg : AEStronglyMeasurable g μ)
    (hinv : (fun ω => g (shift ω)) =ᵐ[μ] g) :
    ∃ g',
      AEStronglyMeasurable[shiftInvariantSigma (α := α)] g' μ ∧
      (∀ᵐ ω ∂μ, g' ω = g ω) ∧
      (∀ ω, g' (shift ω) = g' ω) := by
  classical
  rcases hg with ⟨g0, hg0_sm, hAEg0⟩
  have hcomp :=
    (hσ.quasiMeasurePreserving.ae_eq_comp (μ := μ) (ν := μ)
      (f := shift (α := α)) (g := fun ω => g ω) (g' := fun ω => g0 ω) hAEg0)
  have hshift0 : (fun ω => g0 (shift ω)) =ᵐ[μ] g0 :=
    hcomp.trans (hinv.trans hAEg0)
  let S : Set (Ω[α]) := {ω | g0 (shift ω) = g0 ω}
  have hS_ae : ∀ᵐ ω ∂μ, ω ∈ S := by
    simpa [S, Set.mem_setOf_eq] using hshift0
  have hS_null : μ Sᶜ = 0 := by
    simpa [ae_iff, S, Set.mem_setOf_eq] using hS_ae
  let S∞ : Set (Ω[α]) := ⋂ n : ℕ, (shift^[n]) ⁻¹' S
  have hSinf_null : μ S∞ᶜ = 0 := by
    have hcompl : S∞ᶜ = ⋃ n : ℕ, (shift^[n]) ⁻¹' Sᶜ := by
      classical
      simpa [S∞, Set.preimage_compl]
        using (Set.compl_iInter (fun n : ℕ => (shift^[n]) ⁻¹' S))
    have hpreimage_null : ∀ n : ℕ, μ ((shift^[n]) ⁻¹' Sᶜ) = 0 := by
      intro n
      simpa using ((MeasurePreserving.iterate hσ n).preimage_null hS_null)
    simpa [hcompl] using measure_iUnion_null hpreimage_null
  have hSinf_ae : ∀ᵐ ω ∂μ, ω ∈ S∞ := by
    simpa [ae_iff, S∞] using hSinf_null
  have hSinf_preimage : shift ⁻¹' S∞ = S∞ := by
    classical
    ext ω
    constructor
    · intro hω
      refine Set.mem_iInter.mpr ?_
      intro n
      have := Set.mem_iInter.mp hω (n + 1)
      simpa [Function.iterate_succ] using this
    · intro hω
      have : shift ω ∈ S∞ := by
        refine Set.mem_iInter.mpr ?_
        intro n
        have := Set.mem_iInter.mp hω n
        simpa [Function.iterate_succ, Function.comp] using this
      simpa [Set.mem_preimage] using this
  have hSinf_equiv : ∀ ω, ω ∈ S∞ ↔ shift ω ∈ S∞ := by
    intro ω
    have hmem := congrArg (fun s => ω ∈ s) hSinf_preimage
    simpa [Set.mem_preimage] using hmem
  let g' : Ω[α] → ℝ := fun ω => if ω ∈ S∞ then g0 ω else 0
  have g'_def : g' = Set.indicator S∞ g0 := by
    classical
    funext ω
    by_cases hω : ω ∈ S∞
    · simp [g', hω, Set.indicator_of_mem]
    · simp [g', hω, Set.indicator_of_not_mem]
  have hg'_ae_eq_g0 : (fun ω => g' ω) =ᵐ[μ] g0 := by
    filter_upwards [hSinf_ae] with ω hω
    simp [g', hω]
  have hg'_ae_eq_g : (fun ω => g' ω) =ᵐ[μ] g :=
    hg'_ae_eq_g0.trans hAEg0
  have hshift_g' : ∀ ω, g' (shift ω) = g' ω := by
    intro ω
    by_cases hω : ω ∈ S∞
    · have hshiftω : shift ω ∈ S∞ := (hSinf_equiv ω).1 hω
      have hSω : ω ∈ S := by
        simpa [S] using Set.mem_iInter.mp hω 0
      simp [g', hω, hshiftω, S, hSω]
    · have hshiftω : shift ω ∉ S∞ := by
        exact (not_congr (hSinf_equiv ω)).1 hω
      simp [g', hω, hshiftω]
  -- measurability of the invariant representative
  refine ⟨g', ?_, hg'_ae_eq_g, hshift_g'⟩
  · -- `g'` is measurable with respect to the invariant σ-algebra
    have hshift_meas : Measurable fun ω => g0 (shift ω) :=
      hg0_sm.measurable.comp measurable_shift
    have hS_meas : MeasurableSet S := by
      classical
      have hdiff_meas : Measurable fun ω => g0 (shift ω) - g0 ω :=
        hshift_meas.sub hg0_sm.measurable
      have hset_eq : S = (fun ω => g0 (shift ω) - g0 ω) ⁻¹' {0} := by
        ext ω; simp [S]
      simpa [hset_eq] using hdiff_meas measurableSet_singleton
    have hshift_iter_meas : ∀ n : ℕ, Measurable fun ω => shift^[n] ω := by
      intro n
      induction' n with n ih
      · simpa using measurable_id
      · simpa [Function.iterate_succ, Function.comp] using measurable_shift.comp ih
    have hSinf_meas : MeasurableSet S∞ := by
      classical
      refine MeasurableSet.iInter fun n => ?_
      simpa [S∞] using (hshift_iter_meas n) hS_meas
    have hg0_meas : Measurable g0 := hg0_sm.measurable
    have hg'_meas : Measurable g' := by
      classical
      simpa [g'_def] using hg0_meas.indicator hSinf_meas
    have hg'_meas_shift : Measurable[shiftInvariantSigma] g' := by
      classical
      intro t ht
      have hset_meas : MeasurableSet (g' ⁻¹' t) := hg'_meas ht
      have hset_inv : shift ⁻¹' (g' ⁻¹' t) = g' ⁻¹' t := by
        ext ω; simp [Set.mem_preimage, hshift_g']
      exact (mem_shiftInvariantSigma_iff (g' ⁻¹' t)).mpr ⟨hset_meas, hset_inv⟩
    exact hg'_meas_shift.aestronglyMeasurable

/-- A pointwise shift-invariant function that is ambient-measurable is measurable with
respect to the shift-invariant σ-algebra. -/
lemma measurable_shiftInvariant_of_pointwise (g : Ω[α] → ℝ)
    (hmeas : Measurable g) (hinv : ∀ ω, g (shift ω) = g ω) :
    Measurable[shiftInvariantSigma] g := by
  classical
  intro s hs
  have hset_meas : MeasurableSet (g ⁻¹' s) := hmeas hs
  have hset_eq : shift ⁻¹' (g ⁻¹' s) = g ⁻¹' s := by
    ext ω; simp [Set.mem_preimage, hinv ω]
  exact (mem_shiftInvariantSigma_iff (g ⁻¹' s)).mpr ⟨hset_meas, hset_eq⟩

/-- Functions that are `AEStronglyMeasurable` with respect to the invariant σ-algebra are
almost everywhere fixed by the shift. -/
lemma shiftInvariantSigma_aestronglyMeasurable_ae_shift_eq
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) {f : Ω[α] → ℝ}
    (hf : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ) :
    (fun ω => f (shift ω)) =ᵐ[μ] f := by
  classical
  rcases hf with ⟨g, hg_meas, hfg⟩
  have hcomp :=
    (hσ.quasiMeasurePreserving).ae_eq_comp (μ := μ) (ν := μ)
      (f := shift (α := α)) (g := fun ω => f ω) (g' := fun ω => g ω) hfg
  have hshift : (fun ω => g (shift ω)) =ᵐ[μ] g :=
    EventuallyEq.of_eq (shiftInvariantSigma_measurable_shift_eq g hg_meas.measurable)
  exact hcomp.trans <| hshift.trans hfg.symm

/-- If an `Lp` function is measurable with respect to the invariant σ-algebra, the Koopman
operator fixes it. -/
lemma koopman_eq_self_of_shiftInvariant
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    {f : Lp ℝ 2 μ}
    (hf : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ) :
    koopman shift hσ f = f := by
  classical
  have hcomp :
      (koopman shift hσ f) =ᵐ[μ]
        (fun ω => f (shift ω)) := by
    change MeasureTheory.Lp.compMeasurePreserving (shift (α := α)) hσ f =ᵐ[μ]
        fun ω => f (shift ω)
    simpa [koopman]
      using
        (MeasureTheory.Lp.coeFn_compMeasurePreserving (μ := μ) (μb := μ)
            (p := (2 : ℝ≥0∞)) f hσ)
  have hshift := shiftInvariantSigma_aestronglyMeasurable_ae_shift_eq (μ := μ) hσ hf
  have hfinal : (koopman shift hσ f) =ᵐ[μ] f := hcomp.trans hshift
  exact Lp.ext hfinal

/-- A Koopman-fixed function should be measurable with respect to the invariant σ-algebra.

The key step is to modify a representative of `f` on a null set so that it becomes
pointwise invariant under the shift; the resulting function will then be
`shiftInvariantSigma`-measurable by construction. -/
lemma aestronglyMeasurable_shiftInvariant_of_koopman
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    {f : Lp ℝ 2 μ}
    (hfix : koopman shift hσ f = f) :
    AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ := by
  classical
  /-
  Proof strategy sketch:
  1. Unfold the equality `koopman shift hσ f = f` to obtain the almost-everywhere
     identity `(fun ω => f (shift ω)) =ᵐ[μ] f`.
  2. Choose a strongly measurable representative `g` of `f`.
  3. Apply `exists_shiftInvariantRepresentative` to obtain a version `g'` of `g`
     that is literally shift-invariant and measurable with respect to the
     invariant σ-algebra.
  4. Transport measurability of `g'` back to `f` using the almost everywhere
     equality.

  Implementing steps (3)–(5) will likely require a bespoke lemma about
  modifying functions on null sets to enforce invariance; this will be filled in
  later.
  -/
  -- STEP 1. Extract the a.e. invariance statement from `koopman` equality.
  have hshift : (fun ω => f (shift ω)) =ᵐ[μ] f := by
    have := congrArg (fun g : Lp ℝ 2 μ => g) hfix
    exact this
  -- STEP 2. Choose a strongly measurable representative of `f`.
  have hf_base : AEStronglyMeasurable f μ := by
    simpa using (Lp.aestronglyMeasurable (μ := μ) (p := (2 : ℝ≥0∞)) f)
  obtain ⟨g, hg_meas, hfg⟩ := hf_base
  -- Transport the a.e. invariance to the chosen representative.
  have hshift_g : (fun ω => g (shift ω)) =ᵐ[μ] g := by
    have hcomp := (hσ.quasiMeasurePreserving.ae_eq_comp hfg)
    have hcomp' : (fun ω => g (shift ω)) =ᵐ[μ] (fun ω => f (shift ω)) := by
      simpa using hcomp
    have hshift' : (fun ω => f (shift ω)) =ᵐ[μ] g := hshift.trans hfg
    exact hcomp'.trans hshift'
  -- STEP 3. Produce a shift-invariant representative and relate it to `f`.
  obtain ⟨g', hg'_meas, hAEgg, _⟩ :=
    exists_shiftInvariantRepresentative (μ := μ) hσ g hg_meas hshift_g
  have hAEgg' : (fun ω => g' ω) =ᵐ[μ] g := hAEgg
  have hAEgf : (fun ω => g' ω) =ᵐ[μ] f := hAEgg'.trans hfg
  have hf_meas : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ :=
    (AEStronglyMeasurable.congr hg'_meas hAEgf)
  exact hf_meas

/-- The fixed-point subspace of the Koopman operator.

This is the closed subspace of L²(μ) consisting of equivalence classes of functions
f such that f ∘ shift = f almost everywhere.
-/
def fixedSubspace {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) : Submodule ℝ (Lp ℝ 2 μ) :=
  fixedSpace (koopman shift hσ)

/-- Functions in the fixed-point subspace are exactly those that are a.e. invariant under shift. -/
lemma mem_fixedSubspace_iff {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) (f : Lp ℝ 2 μ) :
    f ∈ fixedSubspace hσ ↔ koopman shift hσ f = f := by
  rfl

/-- The orthogonal projection onto the fixed-point subspace exists (as a closed subspace). -/
lemma fixedSubspace_closed {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    IsClosed (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := by
  classical
  let T := koopman shift hσ
  have hset : (fixedSubspace hσ : Set (Lp ℝ 2 μ)) =
      (fun f : Lp ℝ 2 μ => T f - f) ⁻¹' ({0} : Set (Lp ℝ 2 μ)) := by
    ext f
    rfl
  have hcont : Continuous fun f : Lp ℝ 2 μ => T f - f :=
    (T.continuous.sub continuous_id)
  have hclosed : IsClosed ((fun f : Lp ℝ 2 μ => T f - f) ⁻¹'
      ({0} : Set (Lp ℝ 2 μ))) :=
    IsClosed.preimage hcont isClosed_singleton
  simpa [hset]

/-- Conditional expectation on L² can be viewed as an orthogonal projection.

For a sub-σ-algebra 𝓖, the conditional expectation condexp[𝓖] is the orthogonal
projection from L²(μ) onto L²(𝓖), the closed subspace of functions measurable
with respect to 𝓖.

TODO: Use mathlib's condexpL2 once we have the proper sub-σ-algebra instance.
-/
noncomputable def condexpL2 {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] :
    Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  ((lpMeas ℝ ℝ (shiftInvariantSigma (α := α)) 2 μ).subtypeL).comp
    (MeasureTheory.condExpL2 ℝ ℝ (shiftInvariantSigma_le (α := α)))

/-- Key theorem: The orthogonal projection onto the fixed-point subspace of the Koopman
operator equals the conditional expectation onto the shift-invariant σ-algebra.

This is the bridge between ergodic theory (operator fixed points) and probability
(conditional expectation).
-/
theorem proj_eq_condexp {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    ∃ (P : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ),
      (∀ f, f ∈ fixedSubspace hσ → P f = f) ∧
      (∀ f, P f = condexpL2 (μ := μ) f) := by
  refine ⟨condexpL2 (μ := μ), ?_, ?_⟩
  · intro f hf
    have hfix : koopman shift hσ f = f :=
      (mem_fixedSubspace_iff (hσ := hσ) (f := f)).1 hf
    have hmeas : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ :=
      aestronglyMeasurable_shiftInvariant_of_koopman (hσ := hσ) hfix
    have hf_mem : f ∈ lpMeas ℝ ℝ (shiftInvariantSigma (α := α)) 2 μ := by
      exact (MeasureTheory.mem_lpMeas_iff_aestronglyMeasurable (m := shiftInvariantSigma)
        (m0 := inferInstance) (μ := μ) (p := (2 : ℝ≥0∞)) (f := f)).mpr hmeas
    let fSub : lpMeas ℝ ℝ (shiftInvariantSigma (α := α)) 2 μ := ⟨f, hf_mem⟩
    have hproj :
        MeasureTheory.condExpL2 ℝ ℝ (shiftInvariantSigma_le (α := α)) f = fSub := by
      simpa [MeasureTheory.condExpL2, fSub]
        using Submodule.orthogonalProjection_mem_subspace_eq_self fSub
    unfold condexpL2
    simpa [fSub, hproj]
  · intro f; rfl

/-- The range of conditional expectation onto the invariant σ-algebra equals
the fixed-point subspace. -/
lemma range_condexp_eq_fixedSubspace {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    Set.range (condexpL2 (μ := μ)) =
    (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := by
  classical
  ext f
  constructor
  · -- (⊆) Range of condexpL2 ⊆ fixedSubspace
    intro ⟨g, hg⟩
    rw [← hg]
    -- condexpL2 g is measurable w.r.t. shiftInvariantSigma
    -- hence invariant under shift, so Koopman fixes it
    classical
    have hmeas :
        AEStronglyMeasurable[shiftInvariantSigma (α := α)]
          (condexpL2 (μ := μ) g : Ω[α] → ℝ) μ := by
      simpa using
        (lpMeas.aestronglyMeasurable
          (MeasureTheory.condExpL2 ℝ ℝ (shiftInvariantSigma_le (α := α)) g))
    have hkoop :=
      koopman_eq_self_of_shiftInvariant (hσ := hσ) hmeas
    exact (mem_fixedSubspace_iff (hσ := hσ)
        (f := condexpL2 (μ := μ) g)).mpr hkoop
  · -- (⊇) fixedSubspace ⊆ Range of condexpL2
    intro hf
    -- If f is fixed by Koopman, then f is shift-invariant a.e.
    -- hence measurable w.r.t. shiftInvariantSigma
    -- so f = condexpL2 f
    use f
    have hfix : koopman shift hσ f = f :=
      (mem_fixedSubspace_iff (hσ := hσ) (f := f)).1 hf
    have hmeas : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ :=
      aestronglyMeasurable_shiftInvariant_of_koopman (hσ := hσ) hfix
    have hf_mem : f ∈ lpMeas ℝ ℝ (shiftInvariantSigma (α := α)) 2 μ :=
      (MeasureTheory.mem_lpMeas_iff_aestronglyMeasurable (m := shiftInvariantSigma)
        (m0 := inferInstance) (μ := μ) (p := (2 : ℝ≥0∞)) (f := f)).mpr hmeas
    let fSub : lpMeas ℝ ℝ (shiftInvariantSigma (α := α)) 2 μ := ⟨f, hf_mem⟩
    have hproj :
        MeasureTheory.condExpL2 ℝ ℝ (shiftInvariantSigma_le (α := α)) f = fSub := by
      simpa [MeasureTheory.condExpL2, fSub]
        using Submodule.orthogonalProjection_mem_subspace_eq_self fSub
    unfold condexpL2
    simp [fSub, hproj]

end Exchangeability.DeFinetti
