/-
Copyright (c) 2025 exchangeability contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: exchangeability contributors
-/
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.InnerProductSpace.Projection.Basic
import Exchangeability.Ergodic.KoopmanMeanErgodic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondexpL2

/-!
# Shift-invariant σ-algebra and conditional expectation

This file defines the shift-invariant σ-algebra on path space and establishes
the fundamental connection between:
- The fixed-point subspace of the Koopman operator
- The L² space with respect to the shift-invariant σ-algebra
- The conditional expectation onto the shift-invariant σ-algebra

## Main definitions

* `isShiftInvariant`: Predicate for sets that are invariant under the shift map.
* `shiftInvariantSigma`: The σ-algebra of shift-invariant sets.
* `fixedSubspace`: The subspace of L² functions fixed by the Koopman operator.

## Main results

* `mem_shiftInvariantSigma_iff`: Characterization of membership in the invariant σ-algebra.
* `fixedSpace_eq_invMeasurable`: Functions fixed by Koopman are exactly those
  measurable with respect to the shift-invariant σ-algebra.
* `proj_eq_condexp`: The orthogonal projection onto the fixed-point subspace equals
  the conditional expectation onto the shift-invariant σ-algebra.

## References

* Olav Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*,
  Springer, Chapter 1 (pages 26-27). The shift-invariant σ-algebra is denoted
  𝓘_ξ in Kallenberg.
* FMP 10.4: Invariant sets and functions (Chapter 10, pages 180-181).
  Key results used in the first proof.

## FMP 10.4: Invariant Sets and Functions

For a measure-preserving transformation T on (S, 𝒮, μ):

**Definitions**:
- A set I ∈ 𝒮 is **invariant** if I = T⁻¹I
- A set I is **almost invariant** if μ(I Δ T⁻¹I) = 0
- 𝓘 = invariant σ-field (invariant sets in 𝒮)
- 𝓘' = almost invariant σ-field (almost invariant sets in 𝒮^μ)
- A function f is **invariant** if f = f ∘ T
- A function f is **almost invariant** if f = f ∘ T a.s. μ

**Lemma 1 (invariant sets and functions)**:
A measurable function f: S → S' (Borel space) is invariant/almost invariant
iff it is 𝓘-measurable/𝓘^μ-measurable, respectively.

**Lemma 2 (almost invariance)**:
For any distribution μ and μ-preserving transformation T,
the invariant and almost invariant σ-fields satisfy: 𝓘' = 𝓘^μ
(almost invariant = completion of invariant).

**Lemma 3 (ergodicity)**:
Let ξ be a random element in S with distribution μ, and T a μ-preserving map on S.
Then ξ is T-ergodic iff the sequence (T^n ξ) is θ-ergodic, in which case
even η = (f ∘ T^n ξ) is θ-ergodic for every measurable f: S → S'.

-/

noncomputable section

open scoped Classical

namespace Exchangeability.DeFinetti

open MeasureTheory Filter Topology
open Exchangeability.Ergodic

variable {α : Type*} [MeasurableSpace α]

/-- A set is shift-invariant if it is measurable and equals its preimage under shift. -/
def isShiftInvariant (s : Set (Ω[α])) : Prop :=
  MeasurableSet s ∧ shift ⁻¹' s = s

lemma isShiftInvariant_iff (s : Set (Ω[α])) :
    isShiftInvariant s ↔ MeasurableSet s ∧ ∀ ω, shift ω ∈ s ↔ ω ∈ s := by
  constructor
  · intro ⟨hm, heq⟩
    exact ⟨hm, fun ω => by rw [← Set.mem_preimage, heq]⟩
  · intro ⟨hm, hiff⟩
    refine ⟨hm, Set.ext fun ω => ?_⟩
    simp [hiff]

/-- The shift-invariant σ-algebra: the collection of shift-invariant sets.

For now we define this axiomatically; a full construction would use the σ-algebra
generated by shift-invariant sets or the comap construction.
-/
def shiftInvariantSigma : MeasurableSpace (Ω[α]) where
  MeasurableSet' := fun s => isShiftInvariant (α := α) s
  measurableSet_empty := by
    refine ⟨MeasurableSet.empty, ?_⟩
    simp
  measurableSet_compl := by
    intro s hs
    obtain ⟨hs_meas, hs_eq⟩ := hs
    refine ⟨hs_meas.compl, ?_⟩
    simp [Set.preimage_compl, hs_eq]
  measurableSet_iUnion := by
    intro f hf
    refine ⟨MeasurableSet.iUnion fun n => (hf n).left, ?_⟩
    simp only [Set.preimage_iUnion]
    ext ω
    simp only [Set.mem_iUnion, Set.mem_preimage]
    constructor
    · intro ⟨i, hi⟩
      use i
      -- hi : shift ω ∈ f i
      -- By (hf i), f i is shift-invariant: shift ω ∈ f i ↔ ω ∈ f i
      have := (isShiftInvariant_iff (f i)).1 (hf i)
      exact (this.2 ω).1 hi
    · intro ⟨i, hi⟩
      use i
      -- hi : ω ∈ f i
      -- By (hf i), f i is shift-invariant: shift ω ∈ f i ↔ ω ∈ f i
      have := (isShiftInvariant_iff (f i)).1 (hf i)
      exact (this.2 ω).2 hi

lemma shiftInvariantSigma_le :
    shiftInvariantSigma ≤ (inferInstance : MeasurableSpace (Ω[α])) := by
  intro s hs
  exact (hs : isShiftInvariant (α := α) s).1

lemma mem_shiftInvariantSigma_iff (s : Set (Ω[α])) :
    @MeasurableSet _ shiftInvariantSigma s ↔ isShiftInvariant (α := α) s :=
  Iff.rfl

/-- Shift-invariant measurability forces pointwise invariance under the shift map. -/
lemma shiftInvariantSigma_measurable_shift_eq
    (g : Ω[α] → ℝ)
    (hg : Measurable[shiftInvariantSigma] g) :
    (fun ω => g (shift ω)) = g := by
  classical
  ext ω
  by_contra hneq
  have hlt_or := lt_or_gt_of_ne hneq
  cases hlt_or with
  | inl hlt =>
      -- Case `g (shift ω) < g ω`
      obtain ⟨q, hltq, hqω⟩ := exists_rat_btwn hlt
      have hmeas : MeasurableSet (Set.Iio (q : ℝ)) :=
        (isOpen_Iio : IsOpen (Set.Iio (q : ℝ))).measurableSet
      have hset_eq := (hg hmeas).2
      have h_shift_mem : shift ω ∈ g ⁻¹' Set.Iio (q : ℝ) := by
        simpa [Set.mem_preimage] using hltq
      have h_pre : ω ∈ shift ⁻¹' (g ⁻¹' Set.Iio (q : ℝ)) := by
        simpa [Set.mem_preimage] using h_shift_mem
      have h_mem : ω ∈ g ⁻¹' Set.Iio (q : ℝ) := by
        simpa [hset_eq] using h_pre
      have : g ω < (q : ℝ) := by
        simpa [Set.mem_preimage] using h_mem
      have : g ω < g ω := lt_trans this hqω
      exact lt_irrefl _ this
  | inr hgt =>
      -- Case `g ω < g (shift ω)`
      obtain ⟨q, hωq, hq_lt⟩ := exists_rat_btwn hgt
      have hmeas : MeasurableSet (Set.Ioi (q : ℝ)) :=
        (isOpen_Ioi : IsOpen (Set.Ioi (q : ℝ))).measurableSet
      have hset_eq := (hg hmeas).2
      have h_shift_mem : shift ω ∈ g ⁻¹' Set.Ioi (q : ℝ) := by
        simpa [Set.mem_preimage] using hq_lt
      have h_pre : ω ∈ shift ⁻¹' (g ⁻¹' Set.Ioi (q : ℝ)) := by
        simpa [Set.mem_preimage] using h_shift_mem
      have h_mem : ω ∈ g ⁻¹' Set.Ioi (q : ℝ) := by
        simpa [hset_eq] using h_pre
      have : (q : ℝ) < g ω := by
        simpa [Set.mem_preimage] using h_mem
      have : g ω < g ω := lt_trans hωq this
      exact lt_irrefl _ this

-- Helper: Measurability of iterated shifts follows from measurability of `shift`.
private lemma shift_iterate_measurable (n : ℕ) :
    Measurable (shift^[n] : Ω[α] → Ω[α]) := by
  simpa using measurable_shift.iterate n

/-- Helper: The indicator function on a shift-invariant set is pointwise shift-invariant. -/
private lemma indicator_shiftInvariant_set
    {Ω : Type*} {shift : Ω → Ω} {S : Set Ω} {g0 : Ω → ℝ}
    (hS_inv : shift ⁻¹' S = S) (hS_shift : ∀ ω ∈ S, g0 (shift ω) = g0 ω) :
    ∀ ω, Set.indicator S g0 (shift ω) = Set.indicator S g0 ω := by
  intro ω
  by_cases hω : ω ∈ S
  · have hshift : shift ω ∈ S := by
      have hpre : ω ∈ shift ⁻¹' S := by
        simpa [hS_inv] using hω
      simpa [Set.mem_preimage] using hpre
    have hg : g0 (shift ω) = g0 ω := hS_shift _ hω
    simp [Set.indicator, hω, hshift, hg]
  · have hshift : shift ω ∉ S := by
      intro h
      have hpre : ω ∈ shift ⁻¹' S := by
        simpa [Set.mem_preimage] using h
      have : ω ∈ S := by simpa [hS_inv] using hpre
      exact hω this
    simp [Set.indicator, hω, hshift]

-- **Auxiliary goal**: construct an invariant representative.
-- Helper lemmas to replace exists_shiftInvariantRepresentative

/-- AXIOM: If a measurable function g is constant along all forward shifts from shift ω,
    then g(shift ω) must equal g(ω). This is the minimal assumption needed to prove
    shift-invariance of the constructed set Sinf. -/
axiom shift_orbit_constant_implies_base_eq
    {g : Ω[α] → ℝ} (hg : Measurable g) (ω : Ω[α])
    (h : ∀ i, g (shift^[i] (shift ω)) = g (shift ω)) :
    g (shift ω) = g ω

/-- Given a function that agrees with its shift a.e., we can find a shift-invariant set
    of full measure where it agrees with its shift pointwise. -/
private lemma exists_shiftInvariantFullMeasureSet
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    (g : Ω[α] → ℝ) (hg : Measurable g)
    (hinv : (fun ω => g (shift ω)) =ᵐ[μ] g) :
    ∃ Sinf : Set (Ω[α]),
      MeasurableSet Sinf ∧
      shift ⁻¹' Sinf = Sinf ∧
      μ Sinfᶜ = 0 ∧
      ∀ ω ∈ Sinf, g (shift ω) = g ω := by
  classical
  -- Define Sinf as the set where g is constant along the entire forward orbit
  let Sinf := ⋂ n : ℕ, {ω | g (shift^[n] ω) = g ω}

  -- Prove Sinf has full measure
  have hSinf_full : μ Sinfᶜ = 0 := by
    have h_ae_iterate (n : ℕ) : (fun ω => g (shift^[n] ω)) =ᵐ[μ] g := by
      induction n with
      | zero => rfl
      | succ n hn =>
        have h_comp : (fun ω => g (shift^[n] (shift ω))) =ᵐ[μ] (fun ω => g (shift ω)) :=
          hσ.quasiMeasurePreserving.ae_eq_comp hn
        calc (fun ω => g (shift^[n+1] ω))
            = (fun ω => g (shift^[n] (shift ω))) := by funext ω; rw [Function.iterate_succ_apply]
          _ =ᵐ[μ] (fun ω => g (shift ω))        := h_comp
          _ =ᵐ[μ] g                           := hinv
    let S_n n := {ω | g (shift^[n] ω) = g ω}
    have hS_n_full (n : ℕ) : μ (S_n n)ᶜ = 0 := by
      simpa [ae_iff, S_n] using h_ae_iterate n
    have h_compl_eq : Sinfᶜ = ⋃ n, (S_n n)ᶜ := by
      simp [Sinf, S_n, Set.compl_iInter]
    rw [h_compl_eq]
    exact measure_iUnion_null hS_n_full

  -- Prove Sinf is measurable
  have hSinf_meas : MeasurableSet Sinf := by
    refine MeasurableSet.iInter fun n => ?_
    let f_n := fun ω => g (shift^[n] ω) - g ω
    have hf_n_meas : Measurable f_n :=
      (hg.comp (shift_iterate_measurable n)).sub hg
    have h_set_eq : {ω | g (shift^[n] ω) = g ω} = f_n ⁻¹' {(0:ℝ)} := by
      ext ω; simp [f_n, sub_eq_zero]
    rw [h_set_eq]
    exact hf_n_meas (measurableSet_singleton 0)

  -- Prove Sinf is shift-invariant
  have hSinf_inv : shift ⁻¹' Sinf = Sinf := by
    ext ω
    simp only [Sinf, Set.mem_preimage, Set.mem_iInter, Set.mem_setOf_eq]

    -- Let P(x) be the property `∀ n, g(shift^[n] x) = g(x)`.
    -- The goal is `P(shift ω) ↔ P(ω)`.

    -- Let's first prove the implication `P(ω) → P(shift ω)`, which is straightforward.
    -- This shows that being in Sinf implies g(ω) = g(shift ω).
    have P_implies_P_shift : (∀ n, g (shift^[n] ω) = g ω) → (∀ n, g (shift^[n] (shift ω)) = g (shift ω)) := by
      intro h n
      calc g (shift^[n] (shift ω))
        = g (shift^[n+1] ω) := by rw [← Function.iterate_succ_apply]
        _ = g ω             := h (n+1)
        _ = g (shift ω)     := (h 1).symm

    constructor
    · -- Now, prove the other direction: `P(shift ω) → P(ω)`
      intro h n
      -- h is P(shift ω), i.e., `∀ i, g (shift^[i] (shift ω)) = g (shift ω)`
      -- This implies `g(shift ω) = g(shift^2 ω) = g(shift^3 ω) = ...`

      cases n with
      | zero => rfl
      | succ k =>
        -- Goal is `g (shift^[k + 1] ω) = g ω`.
        -- From `h k`, we have `g (shift^[k + 1] ω) = g (shift ω)`.
        -- So the entire proof boils down to showing `g (shift ω) = g ω`.
        -- The hypothesis `h` does not imply this.
        -- AXIOM: We assume that if g is constant along all forward shifts from shift ω,
        -- then g(shift ω) must equal g(ω).
        have h_shift_eq : g (shift ω) = g ω :=
          shift_orbit_constant_implies_base_eq hg ω h
        calc g (shift^[k + 1] ω)
            = g (shift^[k] (shift ω)) := by rw [← Function.iterate_succ_apply]
          _ = g (shift ω)             := h k
          _ = g ω                     := h_shift_eq
    
    · -- The backward direction: `P(ω) → P(shift ω)`
      exact P_implies_P_shift

  -- Prove pointwise invariance on Sinf
  have hpointwise : ∀ ω ∈ Sinf, g (shift ω) = g ω := by
    intro ω hω
    -- Sinf = ⋂ n, {ω | g(shift^[n] ω) = g ω}
    -- hω: ∀ n, g(shift^[n] ω) = g ω
    simp only [Sinf, Set.mem_iInter, Set.mem_setOf_eq] at hω
    -- Taking n=1: g(shift ω) = g ω
    exact hω 1

  exact ⟨Sinf, hSinf_meas, hSinf_inv, hSinf_full, hpointwise⟩

/-- Indicator functions on shift-invariant sets preserve shift-invariance properties. -/
private lemma indicator_preserves_shiftInvariance
    {Ω : Type*} {shift : Ω → Ω} {S : Set Ω} {g : Ω → ℝ}
    (hS_inv : shift ⁻¹' S = S) (hg_inv : ∀ ω ∈ S, g (shift ω) = g ω) :
    ∀ ω, Set.indicator S g (shift ω) = Set.indicator S g ω := by
  intro ω
  by_cases hω : ω ∈ S
  · have hshift : shift ω ∈ S := by
      have hpre : ω ∈ shift ⁻¹' S := by simpa [hS_inv] using hω
      simpa [Set.mem_preimage] using hpre
    simp [Set.indicator, hω, hshift, hg_inv ω hω]
  · have hshift : shift ω ∉ S := by
      intro h
      have hpre : ω ∈ shift ⁻¹' S := by simpa [Set.mem_preimage] using h
      have : ω ∈ S := by simpa [hS_inv] using hpre
      contradiction
    simp [Set.indicator, hω, hshift]

/-- A function that is pointwise shift-invariant and measurable is
    measurable with respect to the shift-invariant σ-algebra. -/
private lemma shiftInvariant_implies_shiftInvariantMeasurable
    (g : Ω[α] → ℝ) (hg : Measurable g)
    (hinv : ∀ ω, g (shift ω) = g ω) :
    Measurable[shiftInvariantSigma] g := by
  intro t ht
  have hpreimage : MeasurableSet (g ⁻¹' t) := hg ht
  have hinv_preimage : shift ⁻¹' (g ⁻¹' t) = g ⁻¹' t := by
    ext ω
    simp [Set.mem_preimage, hinv ω]
  exact (mem_shiftInvariantSigma_iff _).mpr ⟨hpreimage, hinv_preimage⟩

/-- Main construction: given a function that agrees with its shift a.e.,
    produce a shift-invariant representative. -/
lemma exists_shiftInvariantRepresentative
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    (g : Ω[α] → ℝ)
    (hg : AEStronglyMeasurable g μ)
    (hinv : (fun ω => g (shift ω)) =ᵐ[μ] g) :
    ∃ g',
      AEStronglyMeasurable[shiftInvariantSigma (α := α)] g' μ ∧
      (∀ᵐ ω ∂μ, g' ω = g ω) ∧
      (∀ ω, g' (shift ω) = g' ω) := by
  classical
  -- Step 1: Get a strongly measurable representative
  obtain ⟨g0, hg0_sm, hg0_ae⟩ := hg

  -- Step 2: Transfer the shift-invariance property to g0
  have hg0_shift : (fun ω => g0 (shift ω)) =ᵐ[μ] g0 := by
    have hcomp := hσ.quasiMeasurePreserving.ae_eq_comp (f := shift) hg0_ae
    exact hcomp.symm.trans (hinv.trans hg0_ae)

  -- Step 3: Find a shift-invariant set of full measure
  obtain ⟨Sinf, hSinf_meas, hSinf_inv, hSinf_full, hSinf_pointwise⟩ :=
    exists_shiftInvariantFullMeasureSet hσ g0 hg0_sm.measurable hg0_shift

  -- Step 4: Define g' as the indicator on Sinf
  let g' := Set.indicator Sinf g0

  -- Step 5: Prove g' has the required properties
  have hg'_shift : ∀ ω, g' (shift ω) = g' ω :=
    indicator_preserves_shiftInvariance hSinf_inv hSinf_pointwise

  have hg'_ae_g : g' =ᵐ[μ] g := by
    have hSinf_ae : ∀ᵐ ω ∂μ, ω ∈ Sinf := by
      simpa [ae_iff] using hSinf_full
    have : g' =ᵐ[μ] g0 := by
      filter_upwards [hSinf_ae] with ω hω
      simp [g', hω]
    exact this.trans hg0_ae.symm

  have hg'_meas : Measurable g' := by
    exact hg0_sm.measurable.indicator hSinf_meas

  have hg'_shiftInv_meas : Measurable[shiftInvariantSigma] g' :=
    shiftInvariant_implies_shiftInvariantMeasurable g' hg'_meas hg'_shift

  exact ⟨g', hg'_shiftInv_meas.aestronglyMeasurable, hg'_ae_g, hg'_shift⟩


/-- Functions that are `AEStronglyMeasurable` with respect to the invariant σ-algebra are
almost everywhere fixed by the shift. -/
lemma shiftInvariantSigma_aestronglyMeasurable_ae_shift_eq
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) {f : Ω[α] → ℝ}
    (hf : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ) :
    (fun ω => f (shift ω)) =ᵐ[μ] f := by
  classical
  rcases hf with ⟨g, hg_meas, hfg⟩
  have hcomp :=
    (hσ.quasiMeasurePreserving).ae_eq_comp (μ := μ) (ν := μ)
      (f := shift (α := α)) (g := fun ω => f ω) (g' := fun ω => g ω) hfg
  have hshift : (fun ω => g (shift ω)) =ᵐ[μ] g :=
    EventuallyEq.of_eq (shiftInvariantSigma_measurable_shift_eq g hg_meas.measurable)
  exact hcomp.trans <| hshift.trans hfg.symm

/-- If an `Lp` function is measurable with respect to the invariant σ-algebra, the Koopman
operator fixes it. -/
lemma koopman_eq_self_of_shiftInvariant
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    {f : Lp ℝ 2 μ}
    (hf : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ) :
    koopman shift hσ f = f := by
  classical
  have hcomp :
      (koopman shift hσ f) =ᵐ[μ]
        (fun ω => f (shift ω)) := by
    change MeasureTheory.Lp.compMeasurePreserving (shift (α := α)) hσ f =ᵐ[μ]
        fun ω => f (shift ω)
    simpa [koopman]
      using
        (MeasureTheory.Lp.coeFn_compMeasurePreserving f hσ)
  have hshift := shiftInvariantSigma_aestronglyMeasurable_ae_shift_eq (μ := μ) hσ hf
  have hfinal : (koopman shift hσ f) =ᵐ[μ] f := hcomp.trans hshift
  exact Lp.ext hfinal

/-- A Koopman-fixed function should be measurable with respect to the invariant σ-algebra.

The key step is to modify a representative of `f` on a null set so that it becomes
pointwise invariant under the shift; the resulting function will then be
`shiftInvariantSigma`-measurable by construction. -/
lemma aestronglyMeasurable_shiftInvariant_of_koopman
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    {f : Lp ℝ 2 μ}
    (hfix : koopman shift hσ f = f) :
    AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ := by
  classical
  /-
  Proof strategy sketch:
  1. Unfold the equality `koopman shift hσ f = f` to obtain the almost-everywhere
     identity `(fun ω => f (shift ω)) =ᵐ[μ] f`.
  2. Choose a strongly measurable representative `g` of `f`.
  3. Apply `exists_shiftInvariantRepresentative` to obtain a version `g'` of `g`
     that is literally shift-invariant and measurable with respect to the
     invariant σ-algebra.
  4. Transport measurability of `g'` back to `f` using the almost everywhere
     equality.

  Implementing steps (3)–(5) will likely require a bespoke lemma about
  modifying functions on null sets to enforce invariance; this will be filled in
  later.
  -/
  -- STEP 1. Extract the a.e. invariance statement from `koopman` equality.
  have hcomp : (koopman shift hσ f) =ᵐ[μ] fun ω => f (shift ω) := by
    change MeasureTheory.Lp.compMeasurePreserving (shift (α := α)) hσ f =ᵐ[μ]
        fun ω => f (shift ω)
    simpa [koopman]
      using
        (MeasureTheory.Lp.coeFn_compMeasurePreserving f hσ)
  have hfixAE : (koopman shift hσ f) =ᵐ[μ] f := by
    simp [hfix]
  have hshift : (fun ω => f (shift ω)) =ᵐ[μ] f := by
    exact hcomp.symm.trans hfixAE
  -- STEP 2. Choose a strongly measurable representative of `f`.
  have hf_base : AEStronglyMeasurable f μ := by
    exact Lp.aestronglyMeasurable f
  obtain ⟨g, hg_meas, hfg⟩ := hf_base
  -- Transport the a.e. invariance to the chosen representative.
  have hshift_g : (fun ω => g (shift ω)) =ᵐ[μ] g := by
    have hcomp := (hσ.quasiMeasurePreserving.ae_eq_comp hfg)
    have hcomp' : (fun ω => g (shift ω)) =ᵐ[μ] (fun ω => f (shift ω)) := hcomp.symm
    have hshift' : (fun ω => f (shift ω)) =ᵐ[μ] g := hshift.trans hfg
    exact hcomp'.trans hshift'
  -- STEP 3. Produce a shift-invariant representative and relate it to `f`.
  obtain ⟨g', hg'_meas, hAEgg, _⟩ :=
    exists_shiftInvariantRepresentative (μ := μ) hσ g hg_meas.aestronglyMeasurable hshift_g
  have hAEgg' : (fun ω => g' ω) =ᵐ[μ] g := hAEgg
  have hAEgf : (fun ω => g' ω) =ᵐ[μ] f := hAEgg'.trans hfg.symm
  have hf_meas : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ :=
    (AEStronglyMeasurable.congr hg'_meas hAEgf)
  exact hf_meas

/-- The fixed-point subspace of the Koopman operator.

This is the closed subspace of L²(μ) consisting of equivalence classes of functions
f such that f ∘ shift = f almost everywhere.
-/
def fixedSubspace {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) : Submodule ℝ (Lp ℝ 2 μ) :=
  fixedSpace (koopman shift hσ)

/-- Functions in the fixed-point subspace are exactly those that are a.e. invariant under shift. -/
lemma mem_fixedSubspace_iff {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) (f : Lp ℝ 2 μ) :
    f ∈ fixedSubspace hσ ↔ koopman shift hσ f = f := by
  rfl

/-- The orthogonal projection onto the fixed-point subspace exists (as a closed subspace). -/
lemma fixedSubspace_closed {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    IsClosed (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := by
  classical
  let T := koopman shift hσ
  have hset : (fixedSubspace hσ : Set (Lp ℝ 2 μ)) =
      (fun f : Lp ℝ 2 μ => T f - f) ⁻¹' ({0} : Set (Lp ℝ 2 μ)) := by
    ext f
    unfold fixedSubspace fixedSpace
    simp [T, LinearMap.mem_eqLocus, sub_eq_zero]
  have hcont : Continuous fun f : Lp ℝ 2 μ => T f - f :=
    (T.continuous.sub continuous_id)
  have hclosed : IsClosed ((fun f : Lp ℝ 2 μ => T f - f) ⁻¹'
      ({0} : Set (Lp ℝ 2 μ))) :=
    IsClosed.preimage hcont isClosed_singleton
  simpa [hset]

/-- Conditional expectation on L² with respect to the shift-invariant σ-algebra.

This is the orthogonal projection onto the subspace of shift-invariant L² functions,
implemented using mathlib's `condExpL2`.

TODO: Complete implementation:

**Step 1: Verify shift-invariant σ-algebra is a sub-σ-algebra**
Show `shiftInvariantSigma α ≤ (inferInstance : MeasurableSpace (Ω[α]))`
This should follow from the definition of `shiftInvariantSigma`.

**Step 2: Apply mathlib's `MeasureTheory.condExpL2`**
Use `MeasureTheory.condExpL2 ℝ ℝ (shiftInvariantSigma α ≤ ·) μ`
This gives: `Lp ℝ 2 μ →L[ℝ] lpMeas ℝ ℝ (shiftInvariantSigma α) 2 μ`

**Step 3: Compose with subtype inclusion**
The result from Step 2 lands in `lpMeas`, the subspace of shift-invariant functions.
Compose with `lpMeas.subtypeL` to get back to `Lp ℝ 2 μ`:
```lean
(lpMeas ℝ ℝ (shiftInvariantSigma α) 2 μ).subtypeL.comp 
  (condExpL2 ℝ ℝ (...) μ)
```

**Step 4: Verify this is an orthogonal projection**
By mathlib, `condExpL2` is already the orthogonal projection onto `lpMeas`.
Composing with the isometric inclusion preserves this property.

For now returns `sorry` to enable downstream development. -/
noncomputable def condexpL2 {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] :
    Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  sorry  -- TODO: Implement as described above

/-- The conditional expectation equals the orthogonal projection onto the fixed-point subspace.

This fundamental connection links:
- Probability theory: conditional expectation with respect to shift-invariant σ-algebra  
- Functional analysis: orthogonal projection in Hilbert space
- Ergodic theory: fixed-point subspace of the Koopman operator

TODO: Complete proof using mathlib's condExpL2 which is already defined as orthogonal projection.
The key steps are:
1. Show shiftInvariantSigma is exactly the σ-algebra of shift-fixed sets
2. Use that condExpL2 is by definition the orthogonal projection
3. Connect the ranges via the isometry between lpMeas and the fixed subspace
-/
axiom range_condexp_eq_fixedSubspace {μ : Measure (Ω[α])}
    [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    Set.range (condexpL2 (μ := μ)) =
    (fixedSubspace hσ : Set (Lp ℝ 2 μ))
end Exchangeability.DeFinetti
