/-
Copyright (c) 2025 exchangeability contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: exchangeability contributors
-/
import Mathlib.Probability.ConditionalExpectation
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.Probability.Martingale.Basic
import Exchangeability.Contractability

/-!
# Third proof of de Finetti via a martingale argument

Kallenberg sketches a third proof of Theorem 1.1 (credited to Aldous) which relies
on a martingale argument rather than the mean ergodic theorem or the L²
contractability bound.  This file records the relevant statements so that the
formalisation can proceed in parallel with the other two approaches.

The key ingredients are:

* A *contraction and independence* lemma: if `(ξ, η)` and `(ξ, ζ)` are
  identically distributed and `σ(η) ≤ σ(ζ)`, then `ξ` is conditionally independent
  of `ζ` given `η`.
* For a contractable sequence `ξ`, the extreme members agree almost surely once
  conditioned on the tail σ-algebra.  This yields conditional independence and
  identical conditional laws given the tail σ-algebra, completing the de Finetti
  theorem.

The present file provides Lean statements mirroring Kallenberg's text together
with TODOs for the remaining probabilistic infrastructure (martingales with
values in kernels, etc.).

## References

* Olav Kallenberg, *Probabilistic Symmetries and Invariance Principles* (2005),
  Lemma 1.3 and the third proof of Theorem 1.1 (page 28).
* David Aldous, *Exchangeability and related topics*, École d'Été de
  Probabilités de Saint-Flour XIII (1983).
-/

noncomputable section
open scoped MeasureTheory ProbabilityTheory Topology

namespace Exchangeability
namespace DeFinetti
namespace MartingaleApproach

open MeasureTheory Filter

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-- **Lemma (contraction and independence).**

If `(ξ, η)` and `(ξ, ζ)` have the same distribution and the σ-algebra generated
by `η` is contained in the σ-algebra generated by `ζ`, then `ξ` is conditionally
independent of `ζ` given `η`.

*Kallenberg (2005), Lemma 1.3.* -/
lemma contraction_independence
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {ξ η ζ : Ω → α}
    (h_dist : Measure.map (fun ω => (ξ ω, η ω)) μ
              = Measure.map (fun ω => (ξ ω, ζ ω)) μ)
    (h_sigma : σ ⟨η, by infer_instance⟩ ≤ σ ⟨ζ, by infer_instance⟩) :
    ProbabilityTheory.CondIndep ξ ζ η μ := by
  -- TODO: implement the bounded-martingale argument described by Kallenberg.
  -- Sketch:
  --  * For each measurable set `B`, define μ₁ = P[ξ ∈ B | η] and μ₂ = P[ξ ∈ B | ζ].
  --  * Show `(μ₁, μ₂)` is a bounded martingale with identical marginals.
  --  * Conclude μ₁ = μ₂ almost surely to deduce conditional independence.
  sorry

/-- **Aldous' martingale proof of de Finetti's theorem (skeleton).**

Assume `(Xₙ)` is contractable.  Then the extreme members agree almost surely
after conditioning on the tail σ-algebra, which implies the sequence is
conditionally i.i.d. given the tail σ-algebra `𝒯_X`.

This statement packages the overall strategy; the probabilistic ingredients
remain TODOs. -/
theorem conditionallyIID_of_contractable
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {α : Type*} [MeasurableSpace α]
    (X : ℕ → Ω → α) (h_contr : Contractable μ X) :
    ∃ (ℱ : MeasurableSpace Ω) (ν : Ω → Measure α),
      (∀ ω, IsProbabilityMeasure (ν ω)) ∧
      -- ℱ should specialise to the tail σ-algebra of X once the auxiliary
      -- infrastructure is available; see `Exchangeability.Probability.tailSigmaAlgebra`.
      -- The sequence is conditionally i.i.d. given ℱ with law ν.
      sorry := by
  -- TODO:
  --  * Use contraction_independence with shifts θₖ ξ to deduce conditional
  --    independence of extreme members.
  --  * Apply reverse martingale convergence to show the conditional laws
  --    stabilise on the tail σ-algebra.
  --  * Package ν := P[ξ₁ ∈ · | 𝒯_X].
  --  * Assemble the ConditionallyIID predicate.
  sorry

end MartingaleApproach
end DeFinetti
end Exchangeability
