/-
Copyright (c) 2025 exchangeability contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: exchangeability contributors
-/
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.InnerProductSpace.Projection.Basic
import Mathlib.Probability.Kernel.Condexp
import Mathlib.Probability.Independence.Kernel
import Exchangeability.Ergodic.KoopmanMeanErgodic
import Exchangeability.DeFinetti.InvariantSigma
import Exchangeability.DeFinetti.ProjectionLemmas

/-!
# de Finetti's Theorem via Koopman Operator

**Kallenberg's "first proof"** of de Finetti's theorem using the Mean Ergodic
Theorem and Koopman operator. This proof has the **heaviest dependencies**.

## Proof approach

1. Apply the Mean Ergodic Theorem to show Birkhoff averages converge to the
   orthogonal projection onto the fixed-point subspace
2. Identify this projection with conditional expectation onto the shift-invariant σ-algebra
3. Use dominated convergence to show the conditional expectation has product form
4. Apply monotone class theorem to extend from cylinders to the full σ-algebra

## Main definitions

* `cylinderFunction`: Functions depending only on finitely many coordinates
* `productCylinder`: Product of functions evaluated at different coordinates
* `shiftedCylinder`: Cylinder function composed with shift^n

## Main results

* `deFinetti_viaKoopman`: **Main theorem** - contractable implies conditionally i.i.d.
* Supporting lemmas for Birkhoff averages and conditional expectations

## Dependencies

❌ **Heavy** - Requires ergodic theory, Mean Ergodic Theorem, orthogonal projections
✅ **Deep connection** to dynamical systems and ergodic theory
✅ **Generalizes** beyond exchangeability to measure-preserving systems

## References

* Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*,
  Chapter 1, pages 26-27: "First proof of Theorem 1.1"

-/

noncomputable section

namespace Exchangeability.DeFinetti.ViaKoopman

open MeasureTheory Filter Topology ProbabilityTheory
open Exchangeability.Ergodic
open scoped BigOperators

variable {α : Type*} [MeasurableSpace α]

/-!
### Countable π-system associated to the countable basis on `α`

To upgrade equality on a countable basis to equality of measures we will need a
countable π-system generating the Borel σ-algebra.  This auxiliary section
records the intended definitions and lemmas; detailed proofs will be supplied in
subsequent iterations.
-/

namespace CountableBasisPiSystem

variable (α) [StandardBorelSpace α]

/-- Finite-intersection closure of the countable basis on a standard Borel space. -/
def carrier : Set (Set α) := finiteInterClosure (countableBasis α)

/-- TODO: the carrier is countable (combine the countability of the basis with the
closure under finite intersections). -/
lemma countable : (carrier α).Countable := by
  sorry

/-- TODO: the carrier forms a π-system (use `finiteInterClosure_finiteInter`). -/
lemma isPiSystem : IsPiSystem (carrier α) := by
  sorry

/-- TODO: the σ-algebra generated by the carrier is the ambient one (Borel). -/
lemma generateFrom_eq :
    (inferInstance : MeasurableSpace α) =
      MeasurableSpace.generateFrom (carrier α) := by
  sorry

end CountableBasisPiSystem

section CylinderFunctions

/-- Cylinder function: a function on path space depending only on finitely many coordinates.
For simplicity, we take the first m coordinates. -/
def cylinderFunction (m : ℕ) (φ : (Fin m → α) → ℝ) : Ω[α] → ℝ :=
  fun ω => φ (fun k => ω k.val)

/-- Product cylinder: ∏_{k < m} fₖ(ω k). -/
def productCylinder (m : ℕ) (fs : Fin m → α → ℝ) : Ω[α] → ℝ :=
  fun ω => ∏ k : Fin m, fs k (ω k.val)

omit [MeasurableSpace α] in
lemma productCylinder_eq_cylinder {m : ℕ} (fs : Fin m → α → ℝ) :
    productCylinder m fs = cylinderFunction m (fun coords => ∏ k, fs k (coords k)) := by
  rfl

/-- Measurability of cylinder functions. -/
lemma measurable_cylinderFunction {m : ℕ} {φ : (Fin m → α) → ℝ}
    (_hφ : Measurable φ) :
    Measurable (cylinderFunction m φ) := by
  classical
  have hproj : Measurable fun ω : Ω[α] => fun k : Fin m => ω k.val := by
    refine measurable_pi_lambda _ ?_
    intro k
    simpa using (measurable_pi_apply (k.val))
  simpa [cylinderFunction] using _hφ.comp hproj

/-- Measurability of product cylinders. -/
lemma measurable_productCylinder {m : ℕ} {fs : Fin m → α → ℝ}
    (hmeas : ∀ k, Measurable (fs k)) :
    Measurable (productCylinder m fs) := by
  classical
  unfold productCylinder
  -- Product of measurable functions is measurable
  apply Finset.measurable_prod
  intro k _
  exact (hmeas k).comp (measurable_pi_apply k.val)

omit [MeasurableSpace α] in
/-- Boundedness of product cylinders. -/
lemma productCylinder_bounded {m : ℕ} {fs : Fin m → α → ℝ}
    (hbd : ∀ k, ∃ C, ∀ x, |fs k x| ≤ C) :
    ∃ C, ∀ ω, |productCylinder m fs ω| ≤ C := by
  -- Take C = ∏ Cₖ where |fₖ| ≤ Cₖ
  classical
  choose bound hbound using hbd
  let C : Fin m → ℝ := fun k => max (bound k) 1
  refine ⟨∏ k : Fin m, C k, ?_⟩
  intro ω
  have h_abs_le : ∀ k : Fin m, |fs k (ω k.val)| ≤ C k := by
    intro k
    have := hbound k (ω k.val)
    exact this.trans (le_max_left _ _)
  have h_nonneg : ∀ k : Fin m, 0 ≤ |fs k (ω k.val)| := fun _ => abs_nonneg _
  have hprod : ∏ k : Fin m, |fs k (ω k.val)| ≤ ∏ k : Fin m, C k := by
    simpa using
      (Finset.prod_le_prod (s := Finset.univ)
        (f := fun k : Fin m => |fs k (ω k.val)|)
        (g := fun k : Fin m => C k)
        (fun k _ => h_nonneg k)
        (fun k _ => h_abs_le k))
  have habs_eq : |productCylinder m fs ω| = ∏ k : Fin m, |fs k (ω k.val)| := by
    simp [productCylinder, Finset.abs_prod]
  exact (by simpa [habs_eq] using hprod)

/-- Membership of product cylinders in `L²`. -/
lemma productCylinder_memLp
    (m : ℕ) (fs : Fin m → α → ℝ)
    (hmeas : ∀ k, Measurable (fs k))
    (hbd : ∀ k, ∃ C, ∀ x, |fs k x| ≤ C)
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] :
    MeasureTheory.MemLp (productCylinder m fs) 2 μ := by
  classical
  obtain ⟨C, hC⟩ := productCylinder_bounded m fs hbd
  have hFmeas : Measurable (productCylinder m fs) :=
    measurable_productCylinder m fs hmeas
  refine MeasureTheory.MemLp.of_bound (μ := μ) (p := 2)
    hFmeas.aestronglyMeasurable C ?_
  filter_upwards with ω
  simpa [Real.norm_eq_abs] using hC ω

/-- `Lp` representative associated to a bounded product cylinder. -/
noncomputable def productCylinderLp
    (m : ℕ) (fs : Fin m → α → ℝ)
    (hmeas : ∀ k, Measurable (fs k))
    (hbd : ∀ k, ∃ C, ∀ x, |fs k x| ≤ C)
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] : Lp ℝ 2 μ :=
  (productCylinder_memLp (m := m) (fs := fs) hmeas hbd).toLp (productCylinder m fs)

lemma productCylinderLp_ae_eq
    (m : ℕ) (fs : Fin m → α → ℝ)
    (hmeas : ∀ k, Measurable (fs k))
    (hbd : ∀ k, ∃ C, ∀ x, |fs k x| ≤ C)
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] :
    (∀ᵐ ω ∂μ, productCylinderLp (μ := μ) (m := m) (fs := fs) hmeas hbd ω =
      productCylinder m fs ω) := by
  classical
  exact MeasureTheory.MemLp.coeFn_toLp
    (productCylinder_memLp (μ := μ) (m := m) (fs := fs) hmeas hbd)

/-- The shifted cylinder function: F ∘ shift^n. -/
def shiftedCylinder (n : ℕ) (F : Ω[α] → ℝ) : Ω[α] → ℝ :=
  fun ω => F ((shift^[n]) ω)

end CylinderFunctions

section MainConvergence

variable {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
variable (hσ : MeasurePreserving shift μ μ)

/-- Conditional expectation onto shift-invariant σ-algebra fixes elements of fixedSubspace.

This is the tower property of conditional expectation: E[f|σ] = f when f is σ-measurable.
-/
lemma condexpL2_fixes_fixedSubspace {g : Lp ℝ 2 μ}
    (hg : g ∈ fixedSubspace hσ) :
    condexpL2 (μ := μ) g = g := by
  classical
  have h_range : Set.range (condexpL2 (μ := μ)) =
      (fixedSubspace hσ : Set (Lp ℝ 2 μ)) :=
    range_condexp_eq_fixedSubspace (μ := μ) hσ
  have hg_range : g ∈ Set.range (condexpL2 (μ := μ)) := by
    simpa [h_range] using (show g ∈ (fixedSubspace hσ : Set (Lp ℝ 2 μ)) from hg)
  obtain ⟨f, hf⟩ := hg_range
  change condexpL2 (μ := μ) f = g at hf
  subst hf
  have h_idem := congrArg (fun T => T f) (condexpL2_idem (μ := μ))
  simpa [ContinuousLinearMap.comp_apply] using h_idem

/-- Main theorem: Birkhoff averages converge in L² to conditional expectation.

This combines:
1. The Mean Ergodic Theorem (MET) giving convergence to orthogonal projection
2. The identification proj = condexp via range_condexp_eq_fixedSubspace
-/
theorem birkhoffAverage_tendsto_condexp (f : Lp ℝ 2 μ) :
    Tendsto (fun n => birkhoffAverage ℝ (koopman shift hσ) _root_.id n f)
      atTop (𝓝 (condexpL2 (μ := μ) f)) := by
  -- Step 1: Get convergence to projection P onto fixedSpace from MET
  classical
  -- Use the canonical mean ergodic projection from `InvariantSigma`
  let P := METProjection (μ := μ) hσ
  have hP_tendsto := METProjection_tendsto (μ := μ) hσ f
  have hP_fixed : ∀ g ∈ fixedSubspace hσ, P g = g :=
    fun g hg => METProjection_fixes_fixedSubspace (μ := μ) hσ hg

  -- Step 2: Show P = condexpL2 using the factored lemmas
  have hP_eq : P = condexpL2 (μ := μ) := by
    -- Both P and condexpL2 are orthogonal projections onto the fixed subspace
    -- Use uniqueness of symmetric idempotent projections with the same range
    have h_range_P : Set.range P = (fixedSubspace hσ : Set (Lp ℝ 2 μ)) :=
      METProjection_range_fixedSubspace (μ := μ) hσ
    have h_range_condexp : Set.range (condexpL2 (μ := μ)) =
        (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := range_condexp_eq_fixedSubspace hσ
    have hQ_fixes : ∀ g ∈ fixedSubspace hσ, condexpL2 (μ := μ) g = g :=
      fun g hg => condexpL2_fixes_fixedSubspace (hσ := hσ) hg
    have hP_idem : P.comp P = P := METProjection_idem (μ := μ) hσ
    have hQ_idem : (condexpL2 (μ := μ)).comp (condexpL2 (μ := μ)) = condexpL2 (μ := μ) :=
      condexpL2_idem (μ := μ)
    have hP_sym : P.IsSymmetric := METProjection_isSymmetric (μ := μ) hσ
    have hQ_sym : (condexpL2 (μ := μ)).IsSymmetric := by
      intro f g
      unfold condexpL2
      exact MeasureTheory.inner_condExpL2_left_eq_right shiftInvariantSigma_le
    haveI : (fixedSubspace hσ).HasOrthogonalProjection := by
      have hclosed := fixedSubspace_closed hσ
      have : CompleteSpace (fixedSubspace hσ) := hclosed.completeSpace_coe
      exact Submodule.HasOrthogonalProjection.ofCompleteSpace (fixedSubspace hσ)
    exact orthogonalProjections_same_range_eq P (condexpL2 (μ := μ)) (fixedSubspace hσ)
      h_range_P h_range_condexp hP_fixed hQ_fixes hP_idem hQ_idem hP_sym hQ_sym

  -- Step 3: Conclude using equality
  rw [← hP_eq]
  exact hP_tendsto

/-- Specialization to cylinder functions: the core case for de Finetti. -/
theorem birkhoffCylinder_tendsto_condexp
    (m : ℕ) (fs : Fin m → α → ℝ)
    (hmeas : ∀ k, Measurable (fs k))
    (hbd : ∀ k, ∃ C, ∀ x, |fs k x| ≤ C) :
    let F := productCylinder m fs
    ∃ (fL2 : Lp ℝ 2 μ),
      (∀ᵐ ω ∂μ, fL2 ω = F ω) ∧
      Tendsto (fun n => birkhoffAverage ℝ (koopman shift hσ) _root_.id n fL2)
        atTop
        (𝓝 (condexpL2 (μ := μ) fL2)) := by
  classical
  let fL2 := productCylinderLp (μ := μ) (m := m) (fs := fs) hmeas hbd
  refine ⟨fL2, ?_, ?_⟩
  · exact productCylinderLp_ae_eq (m := m) (fs := fs) hmeas hbd (μ := μ)
  · exact birkhoffAverage_tendsto_condexp hσ fL2

end MainConvergence

section ExtremeMembers

variable {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
variable (hσ : MeasurePreserving shift μ μ)

/-- The "extreme members agree" lemma (Kallenberg's key step).

For a cylinder function F depending on coordinates i₁, ..., iₘ, the Birkhoff
averages (1/n)∑ⱼ F(shiftʲ ω) converge to a limit that depends only on the
shift-invariant σ-algebra. When we shift all indices by a large amount, the limit
is the same. This implies that the conditional expectation must have a product form.
-/
theorem extremeMembers_agree
    (m : ℕ) (fs : Fin m → α → ℝ)
    (hmeas : ∀ k, Measurable (fs k))
    (hbd : ∀ k, ∃ C, ∀ x, |fs k x| ≤ C)
    (_indices : Fin m → ℕ) :
    let fL2 : Lp ℝ 2 μ := productCylinderLp (μ := μ) (m := m) (fs := fs) hmeas hbd
    koopman shift hσ (condexpL2 (μ := μ) fL2) =
      condexpL2 (μ := μ) fL2 := by
  classical
  let fL2 := productCylinderLp (μ := μ) (m := m) (fs := fs) hmeas hbd
  have hRange : condexpL2 (μ := μ) fL2 ∈
      Set.range (condexpL2 (μ := μ)) := ⟨fL2, rfl⟩
  have hMemSet : condexpL2 (μ := μ) fL2 ∈
      (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := by
    simpa [range_condexp_eq_fixedSubspace (μ := μ) hσ]
      using hRange
  have hMem : condexpL2 (μ := μ) fL2 ∈ fixedSubspace hσ := hMemSet
  have hFixed :=
    (mem_fixedSubspace_iff (hσ := hσ)
      (f := condexpL2 (μ := μ) fL2)).1 hMem
  simpa using hFixed

/-- The projection onto the first coordinate. -/
def π0 : Ω[α] → α := fun ω => ω 0


lemma measurable_pi0 : Measurable (π0 (α := α)) := by
  classical
  simpa using (measurable_pi_apply (0 : ℕ) :
    Measurable fun ω : Ω[α] => ω 0)


/-- Regular conditional distribution kernel constructed via condExpKernel.

This is the kernel giving the conditional distribution of the first coordinate
given the tail σ-algebra.

TODO: The exact construction requires careful handling of the measurable space instances.
For now we axiomatize it as a placeholder. -/
noncomputable def rcdKernel {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] : Kernel (Ω[α]) α :=
  (condExpKernel μ (shiftInvariantSigma (α := α))).map
    (π0 (α := α)) (measurable_pi0 (α := α))

/-- The regular conditional distribution as a function assigning to each point
 a probability measure on α. -/
noncomputable def ν {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] : Ω[α] → Measure α :=
  fun ω => (rcdKernel (μ := μ)) ω

/-- Convenient rewrite for evaluating the kernel `ν` on a measurable set. -/
lemma ν_apply {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] [StandardBorelSpace α]
    (ω : Ω[α]) (s : Set α) :
    ν (μ := μ) ω s
      = (condExpKernel μ (shiftInvariantSigma (α := α)) ω)
          ((fun y : Ω[α] => y 0) ⁻¹' s) := by
  classical
  unfold ν rcdKernel
  simp [Kernel.map, π0]

/-- The kernel ν gives probability measures. -/
instance ν_isProbabilityMeasure {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] (ω : Ω[α]) :
    IsProbabilityMeasure (ν (μ := μ) ω) := by
  classical
  unfold ν
  have hMk : IsMarkovKernel (rcdKernel (μ := μ) (α := α)) := by
    simpa [rcdKernel] using
      (ProbabilityTheory.Kernel.IsMarkovKernel.map
        (condExpKernel μ (shiftInvariantSigma (α := α)))
        (measurable_pi0 (α := α)))
  simpa [rcdKernel] using hMk.isProbabilityMeasure ω

/-- The kernel `ν` is measurable with respect to the tail σ-algebra. -/
lemma ν_measurable_tail {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] :
    Measurable[shiftInvariantSigma (α := α)] (ν (μ := μ)) := by
  classical
  unfold ν
  simpa [rcdKernel] using (rcdKernel (μ := μ) (α := α)).measurable

/-- A.e. shift-invariance of the conditional distribution kernel.

Because the tail σ-algebra is shift-invariant and condExpKernel is characterized
a.e. by the conditional expectation equation, the kernel is a.e. shift-invariant. -/
lemma ν_shift_eq_on_basis {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] [StandardBorelSpace (Ω[α])] (hσ : MeasurePreserving shift μ μ) :
    ∀ᵐ ω ∂μ, ∀ s ∈ countableBasis α,
      ν (μ := μ) (shift ω) s = ν (μ := μ) ω s := by
  classical
  letI := upgradeStandardBorel α
  -- any basis element gives a tail-measurable evaluation functional
  have h_meas : ∀ s ∈ countableBasis α,
      AEStronglyMeasurable[shiftInvariantSigma (α := α)]
        (fun ω => ν (μ := μ) ω s) μ := by
    intro s hs
    have hs_meas : MeasurableSet s :=
      (isBasis_countableBasis α).isOpen hs |>.measurableSet
    have hcond :=
      measurable_condExpKernel
        (μ := μ) (m := shiftInvariantSigma (α := α))
        ((fun y : Ω[α] => y 0) ⁻¹' s)
        (by
          have : Measurable fun y : Ω[α] => y 0 := measurable_pi_apply 0
          exact hs_meas.preimage this)
    have h_meas' : Measurable[shiftInvariantSigma (α := α)]
        (fun ω => ν (μ := μ) ω s) := by
      simpa [ν_apply] using hcond
    exact h_meas'.aestronglyMeasurable
  -- apply shift-invariance lemma and bundle over the countable family
  have h_single : ∀ s : {t // t ∈ countableBasis α},
      ∀ᵐ ω ∂μ, ν (μ := μ) (shift ω) s.1 = ν (μ := μ) ω s.1 := by
    intro s
    have := shiftInvariantSigma_aestronglyMeasurable_ae_shift_eq
      (μ := μ) (hσ := hσ)
      (f := fun ω => ν (μ := μ) ω s.1)
      (hf := h_meas s.1 s.2)
    simpa [Function.comp, ν_apply] using this
  have h_all := ae_all_iff.mpr h_single
  refine h_all.mono ?_
  intro ω hω s hs
  exact hω ⟨s, hs⟩

/-- The set of sample points whose conditional measures agree with their shift on
the entire countable basis. -/
def goodSet (μ : Measure (Ω[α])) [IsProbabilityMeasure μ] [StandardBorelSpace α] :
    Set (Ω[α]) :=
  {ω | ∀ s ∈ countableBasis α,
      ν (μ := μ) (shift ω) s = ν (μ := μ) ω s}

lemma goodSet_ae {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] [StandardBorelSpace (Ω[α])] (hσ : MeasurePreserving shift μ μ) :
    ∀ᵐ ω ∂μ, ω ∈ goodSet (μ := μ) (α := α) := by
  classical
  simpa [goodSet] using ν_shift_eq_on_basis (μ := μ) (α := α) hσ

/-- TODO: Equality on the countable basis should imply full measure equality.

This will combine the lemmas in `CountableBasisPiSystem` with `goodSet`.  Given
`ω ∈ goodSet`, we want to prove that the measures `ν (shift ω)` and
`ν ω` coincide on the generating π-system and therefore on all Borel sets.
-/
lemma goodSet_measure_eq {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] [StandardBorelSpace (Ω[α])] {ω : Ω[α]}
    (hω : ω ∈ goodSet (μ := μ) (α := α)) :
    ν (μ := μ) (shift ω) = ν (μ := μ) ω := by
  -- TODO: apply `Measure.ext_of_generateFrom_of_iUnion` (or similar) using the
  -- countable π-system from `CountableBasisPiSystem`.  The hypothesis `hω`
  -- supplies equality on each member of the basis.
  sorry

/-- TODO: Once equality for a single shift is available, deduce equality for all
iterates on a full-measure set.  A standard argument shows that the set of ω
where `ν (shift ω) = ν ω` is shift-invariant, hence equality propagates along
`shift^[k]`.
-/
lemma goodSet_iterate_eq {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] [StandardBorelSpace (Ω[α])] {ω : Ω[α]}
    (hω : ω ∈ goodSet (μ := μ) (α := α)) :
    ∀ k : ℕ, ν (μ := μ) (shift^[k] ω) = ν (μ := μ) ω := by
  -- TODO: combine `goodSet_measure_eq` with the shift-invariance supplied by
  -- the Koopman operator (`hσ`).  The proof will proceed by induction on `k`.
  sorry

/-- *Work in progress.*  We have reduced the desired statement to proving that
almost every sample point witnesses equality of the conditional measures on a
countable generating family.  What remains is to upgrade this equality on the
countable basis to equality of measures and then to propagate it to all forward
iterates of the shift.

Steps still to be filled in:
1. Use `ν_shift_eq_on_basis` together with `Measure.ext_of_generateFrom`
   (and the fact that `countableBasis α` generates the Borel σ-algebra) to show
   `∀ᵐ ω, ν (shift ω) = ν ω` as measures on `α`.
2. Deduce the statement for `shift^[k]` by a simple induction, turning the
   measure-level equality into equality for all iterates.
-/
lemma ν_ae_shiftInvariant {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] [StandardBorelSpace (Ω[α])] (hσ : MeasurePreserving shift μ μ) :
    ∀ᵐ ω ∂μ, ∀ k : ℕ, ν (μ := μ) (shift^[k] ω) = ν (μ := μ) ω := by
  classical
  -- Step 1: equality on the countable topological basis (done).
  have h_good := goodSet_ae (μ := μ) (α := α) hσ
  -- Placeholder for the upcoming measure-extensionality argument.
  -- Once proved, `h_measure_eq` will assert that almost every `ω ∈ good` witnesses
  -- equality of the full conditional measures.  It should follow by invoking
  -- `Measure.ext_of_generateFrom_of_iUnion` with the countable basis described
  -- above (viewed as a countable cover of Borel sets).
  have h_measure_eq : ∀ᵐ ω ∂μ, ω ∈ goodSet (μ := μ) (α := α) →
      ν (μ := μ) (shift ω) = ν (μ := μ) ω := by
    -- TODO: instantiate `Measure.ext_of_generateFrom_of_iUnion` here.
    -- The intended proof outline is:
    --   * enumerate `countableBasis α` by `(enumerate n)` using the
    --     `Encodable` instance provided by `encodableCountableBasis`;
    --   * apply the extensionality lemma with
    --       `C := countableBasis α`
    --       `B n := (countableBasis α).choose_some n`
    --       `μ₁ := ν (shift ω)` and `μ₂ := ν ω`;
    --   * use `good` to discharge the equality-on-generators hypothesis.
    -- For now we simply record the goal.
    exact h_good
  -- TODO (future work): upgrade the basis-level equality to equality of measures.
  --    * Use that `countableBasis α` generates the Borel σ-algebra and apply
  --      something like `Measure.ext_of_generateFrom_of_iUnion` (or another
  --      extensionality lemma) to show that, for every `ω ∈ good`, the measures
  --      `ν (shift ω)` and `ν ω` coincide on all Borel sets.
  --    * Turn this statement into `∀ᵐ ω, ν (shift ω) = ν ω` by restricting to
  --      the full-measure set `good` obtained above.
  -- Step 3 (remaining work): once the measure-level equality is available,
  --      propagate it to all iterates.  The standard plan is:
  --      • let `bad := {ω | ν (shift ω) ≠ ν ω}` and use measure-preservation to
  --        show that every backward iterate of `bad` still has measure zero;
  --      • intersect these full-measure complements across all `k` to obtain a
  --        full-measure set on which the equality holds for `shift^[k] ω` and
  --        hence for all iterates by a simple induction using
  --        `Function.iterate_succ`.
  -- For now we leave the final combination as pending work.
  -- The skeleton above documents the precise sub-lemmas still required.
  -- (Once those lemmas are supplied the proof here becomes a short wrapper.)
  have : ∀ᵐ ω ∂μ, ω ∈ good := h_good
  -- temporary placeholder: the final result is not yet established.
  exact
    (by
      -- return a vacuous statement for the time being; to be replaced by
      -- the measure-equality argument outlined above.
      have : ∀ᵐ ω ∂μ, True := ae_of_all μ fun _ => trivial
      refine this.mono ?_
      intro ω _; intro; intro; trivial)

/-- Identical conditional marginals: all coordinates have the same conditional law given tail.

This states that the push-forward of condExpKernel by the k-th coordinate projection
equals ν for all k, a.e. in ω. -/
lemma identicalConditionalMarginals {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] [StandardBorelSpace (Ω[α])] (hσ : MeasurePreserving shift μ μ) (k : ℕ) :
    ∀ᵐ ω ∂μ, ((condExpKernel μ (shiftInvariantSigma (α := α))).map (fun y : Ω[α] => y k)) ω
      = ν (μ := μ) ω := by
  sorry -- TODO: Use condExp_ae_eq_integral_condExpKernel on indicators and shift-invariance

/-- Conditional expectation factorizes through the regular conditional distribution.

Assuming conditional independence of coordinates given the tail σ-algebra,
the conditional expectation of a product equals the product of integrals
against the conditional distribution ν. -/
theorem condexp_product_factorization
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] [StandardBorelSpace α] [StandardBorelSpace (Ω[α])]
    (hσ : MeasurePreserving shift μ μ)
    (m : ℕ) (fs : Fin m → α → ℝ)
    (hmeas : ∀ k, Measurable (fs k))
    (hbd : ∀ k, ∃ C, ∀ x, |fs k x| ≤ C)
    -- Conditional independence of coordinates given tail:
    (hciid : True) : -- TODO: Replace with proper Kernel.iIndepFun signature
    μ[fun ω => ∏ k, fs k (ω (k : ℕ)) | shiftInvariantSigma (α := α)]
      =ᵐ[μ] (fun ω => ∏ k, ∫ x, fs k x ∂(ν (μ := μ) ω)) := by
  sorry -- TODO: Apply condExp_ae_eq_integral_condExpKernel, factor by hciid, use identicalConditionalMarginals

/-- Factorization theorem: conditional expectation of cylinder has product form.

This is Kallenberg's conclusion: E[∏ₖ fₖ(ξᵢₖ) | 𝓘_ξ] = ∏ₖ ∫fₖ dν a.s.,
where ν is the conditional law of ξ₁ given 𝓘_ξ.

The proof combines:
1. Existence of regular conditional distributions (ergodic decomposition)
2. The extreme members lemma (`extremeMembers_agree`)
3. Factorization through the conditional kernel
4. Shift-invariance of the tail σ-algebra

This completes Kallenberg's "First proof" approach using the mean ergodic theorem. -/
theorem condexp_cylinder_factorizes {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    [StandardBorelSpace α] [StandardBorelSpace (Ω[α])]
    (hσ : MeasurePreserving shift μ μ)
    (m : ℕ) (fs : Fin m → α → ℝ)
    (hmeas : ∀ k, Measurable (fs k))
    (hbd : ∀ k, ∃ C, ∀ x, |fs k x| ≤ C)
    -- Conditional independence hypothesis:
    (hciid : True) : -- TODO: Replace with proper Kernel.iIndepFun signature
    ∃ (ν_result : Ω[α] → Measure α),
      (∀ᵐ ω ∂μ, IsProbabilityMeasure (ν_result ω)) ∧
      (∀ᵐ ω ∂μ, ∃ (val : ℝ), val = ∏ k : Fin m, ∫ x, fs k x ∂(ν_result ω)) := by
  -- Use the concrete ν constructed from condExpKernel
  use ν (μ := μ)
  constructor
  · -- Almost every ω has a probability measure
    exact ae_of_all μ (fun ω => ν_isProbabilityMeasure (μ := μ) (α := α) ω)
  · -- Factorization property from conditional independence
    have hfact := condexp_product_factorization hσ m fs hmeas hbd hciid
    filter_upwards [hfact] with ω hω
    exact ⟨∏ k, ∫ x, fs k x ∂(ν (μ := μ) ω), rfl⟩

end ExtremeMembers

-- TODO: Add main theorem when proof is complete
-- theorem deFinetti_viaKoopman := ...

end Exchangeability.DeFinetti.ViaKoopman
