/-
Copyright

This file is part of the leantest-afp project.
-/
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
import Mathlib.Probability.IdentDistrib
import Mathlib.Probability.Kernel.Basic
import LeantestAfp.Probability.Exchangeability

/-!
# De Finetti's theorem (draft blueprint)

This module sketches the high-level interfaces that will be used in the
formalization of de Finetti's theorem.  The goal is to organise the
probability-theoretic ingredients in a way that matches the accompanying
blueprint document.

The main theorem to be formalised asserts that an infinite exchangeable
sequence of real-valued random variables is conditionally i.i.d. given a
random probability measure (the directing measure).  The proof will follow
the classical path: construct the tail $\sigma$-algebra, use martingale
convergence for the empirical measures, and show that the directing measure
recovers the joint moments of the sequence.

At this early stage we record the key definitions and intermediate lemmas as
`TODO`s so that the blueprint can reference them.

## References
* Bruno De Finetti, *La prévision : ses lois logiques, ses sources
  subjectives*, Annales de l'institut Henri Poincaré (1937).
* David Aldous, *Exchangeability and related topics*, École d'Été de
  Probabilités de Saint-Flour XIII (1983).

-/

noncomputable section
open scoped BigOperators MeasureTheory Topology Classical

namespace LeantestAfp
namespace Probability

open MeasureTheory Filter

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-- The tail `σ`-algebra generated by the tails of the process `X`.  It is the
intersection of the `σ`-algebras generated by the coordinates from `n`
onwards. -/
def tailSigmaAlgebra (X : ℕ → Ω → α) : MeasurableSpace Ω :=
  ⨅ n : ℕ, MeasurableSpace.comap (fun ω => fun k : ℕ => X (n + k) ω) inferInstance

/-!
## Directing measures and conditional laws
-/

/-- Placeholder predicate expressing that `X` is conditionally i.i.d. given the
tail `σ`-algebra with conditional law `K`.  The precise formulation will be
specified once the surrounding theory is available. -/
def ConditionallyIID (μ : Measure Ω) (X : ℕ → Ω → α)
    (K : Ω → ProbabilityMeasure α) : Prop :=
  True


/-- A *directing measure* for an exchangeable process assigns to almost every
sample point `ω` a probability measure on `α` such that conditionally on the tail
`σ`-algebra the process becomes i.i.d.  We model it as a kernel
`Ω → ProbabilityMeasure α`.

`TODO`: define this in terms of `ProbabilityTheory.ConditionalIndependence` once
all prerequisites are in place.
-/
structure DirectingMeasure (Ω α : Type*) [MeasurableSpace Ω] [MeasurableSpace α]
    (μ : Measure Ω) where
  kernel : Ω → ProbabilityMeasure α
  -- TODO: record measurability and tail invariance properties of the kernel
  -- For example: `AEStronglyMeasurable kernel μ` once the definition is in place.

/-- The empirical measures associated with the first `n` coordinates of the
process.  We will show that they converge almost surely and in `L¹` to the
random directing measure.

`TODO`: express the empirical measure using `Measure.map` and `Counting measure`.
-/
def empiricalMeasure (X : ℕ → Ω → α) (n : ℕ) : Ω → ProbabilityMeasure α :=
  sorry

/-!
## Statement of de Finetti's theorem
-/

/-- Draft statement for de Finetti's theorem.  The final statement will show
that every exchangeable process is conditionally i.i.d. given a directing
measure.  At present this is just a placeholder so that downstream lemmas can
refer to it.
-/
theorem deFinetti
    {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    (μ : Measure Ω) [IsProbabilityMeasure μ]
    (X : ℕ → Ω → α) (hX : Exchangeable μ X) :
    ∃ (ξ : DirectingMeasure Ω α μ),
      ConditionallyIID μ X ξ.kernel :=
  sorry

end Probability
end LeantestAfp
