/-
Copyright (c) 2025 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.Topology.Algebra.Order.LiminfLimsup
import Exchangeability.PathSpace.Shift

/-!
# Shift-invariant σ-algebra on path space

This file defines the shift-invariant σ-algebra on path space and establishes
basic measurability properties.

## Main definitions

* `tailSigma`: The tail σ-algebra generated by the iterates of the left shift.
* `isShiftInvariant`: Predicate for sets that are invariant under the shift map.
* `shiftInvariantSigma`: The σ-algebra of shift-invariant sets.

## Main results

* `isShiftInvariant_iff`: Characterization of shift-invariance in terms of membership.
* `shiftInvariantSigma_le`: The shift-invariant σ-algebra is a sub-σ-algebra.
* `mem_shiftInvariantSigma_iff`: Membership in the invariant σ-algebra.
* `shiftInvariantSigma_measurable_shift_eq`: Shift-invariant measurability forces
  pointwise invariance under the shift map.

## References

* Olav Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*,
  Springer, Chapter 1 (pages 26-27). The shift-invariant σ-algebra is denoted
  𝓘_ξ in Kallenberg.
* FMP 10.4: Invariant sets and functions (Chapter 10, pages 180-181).

-/

noncomputable section

open scoped Classical Topology

namespace Exchangeability.DeFinetti

open MeasureTheory Filter Topology
open Exchangeability.PathSpace

variable {α : Type*} [MeasurableSpace α]

/-- The tail σ-algebra generated by the iterates of the left shift on path space. -/
def tailSigma : MeasurableSpace (Ω[α]) :=
  ⨅ n : ℕ, MeasurableSpace.comap (fun ω => (shift^[n]) ω) inferInstance

/-- A set is shift-invariant if it is measurable and equals its preimage under shift. -/
def isShiftInvariant (s : Set (Ω[α])) : Prop :=
  MeasurableSet s ∧ shift ⁻¹' s = s

lemma isShiftInvariant_iff {s : Set (Ω[α])} :
    isShiftInvariant s ↔ MeasurableSet s ∧ ∀ ω, shift ω ∈ s ↔ ω ∈ s := by
  constructor
  · intro ⟨hm, heq⟩
    exact ⟨hm, fun ω => by rw [← Set.mem_preimage, heq]⟩
  · intro ⟨hm, hiff⟩
    refine ⟨hm, Set.ext fun ω => ?_⟩
    simp [hiff]

/-- The shift-invariant σ-algebra: the collection of shift-invariant sets.

This is defined directly as the sub-σ-algebra of measurable shift-invariant sets.
-/
def shiftInvariantSigma : MeasurableSpace (Ω[α]) where
  MeasurableSet' := fun s => isShiftInvariant (α := α) s
  measurableSet_empty := by
    refine ⟨MeasurableSet.empty, ?_⟩
    simp
  measurableSet_compl := by
    intro s hs
    obtain ⟨hs_meas, hs_eq⟩ := hs
    refine ⟨hs_meas.compl, ?_⟩
    simp [Set.preimage_compl, hs_eq]
  measurableSet_iUnion := by
    intro f hf
    refine ⟨MeasurableSet.iUnion fun n => (hf n).1, ?_⟩
    simp only [Set.preimage_iUnion]
    ext ω
    simp only [Set.mem_iUnion, Set.mem_preimage]
    constructor
    · intro ⟨i, hi⟩
      use i
      -- hi : shift ω ∈ f i
      -- By (hf i), f i is shift-invariant: shift ω ∈ f i ↔ ω ∈ f i
      have := isShiftInvariant_iff.1 (hf i)
      exact (this.2 ω).1 hi
    · intro ⟨i, hi⟩
      use i
      -- hi : ω ∈ f i
      -- By (hf i), f i is shift-invariant: shift ω ∈ f i ↔ ω ∈ f i
      have := isShiftInvariant_iff.1 (hf i)
      exact (this.2 ω).2 hi

lemma shiftInvariantSigma_le :
    shiftInvariantSigma ≤ (inferInstance : MeasurableSpace (Ω[α])) := by
  intro s hs
  exact hs.1

lemma mem_shiftInvariantSigma_iff {s : Set (Ω[α])} :
    @MeasurableSet _ shiftInvariantSigma s ↔ isShiftInvariant (α := α) s := Iff.rfl

/-- Shift-invariant measurability forces pointwise invariance under the shift map. -/
lemma shiftInvariantSigma_measurable_shift_eq
    (g : Ω[α] → ℝ)
    (hg : Measurable[shiftInvariantSigma] g) :
    (fun ω => g (shift ω)) = g := by
  classical
  ext ω
  by_contra hneq
  have hlt_or := lt_or_gt_of_ne hneq
  cases hlt_or with
  | inl hlt =>
      -- Case `g (shift ω) < g ω`
      obtain ⟨q, hltq, hqω⟩ := exists_rat_btwn hlt
      have hmeas : MeasurableSet (Set.Iio (q : ℝ)) :=
        (isOpen_Iio : IsOpen (Set.Iio (q : ℝ))).measurableSet
      have hset_eq := (hg hmeas : isShiftInvariant (g ⁻¹' Set.Iio ↑q)).2
      have h_shift_mem : shift ω ∈ g ⁻¹' Set.Iio (q : ℝ) := by
        simpa [Set.mem_preimage] using hltq
      have h_pre : ω ∈ shift ⁻¹' (g ⁻¹' Set.Iio (q : ℝ)) := by
        simpa [Set.mem_preimage] using h_shift_mem
      have h_mem : ω ∈ g ⁻¹' Set.Iio (q : ℝ) := by
        simpa [hset_eq] using h_pre
      have : g ω < (q : ℝ) := by
        simpa [Set.mem_preimage] using h_mem
      have : g ω < g ω := lt_trans this hqω
      exact lt_irrefl _ this
  | inr hgt =>
      -- Case `g ω < g (shift ω)`
      obtain ⟨q, hωq, hq_lt⟩ := exists_rat_btwn hgt
      have hmeas : MeasurableSet (Set.Ioi (q : ℝ)) :=
        (isOpen_Ioi : IsOpen (Set.Ioi (q : ℝ))).measurableSet
      have hset_eq := (hg hmeas : isShiftInvariant (g ⁻¹' Set.Ioi ↑q)).2
      have h_shift_mem : shift ω ∈ g ⁻¹' Set.Ioi (q : ℝ) := by
        simpa [Set.mem_preimage] using hq_lt
      have h_pre : ω ∈ shift ⁻¹' (g ⁻¹' Set.Ioi (q : ℝ)) := by
        simpa [Set.mem_preimage] using h_shift_mem
      have h_mem : ω ∈ g ⁻¹' Set.Ioi (q : ℝ) := by
        simpa [hset_eq] using h_pre
      have : (q : ℝ) < g ω := by
        simpa [Set.mem_preimage] using h_mem
      have : g ω < g ω := lt_trans hωq this
      exact lt_irrefl _ this

-- Helper: Measurability of iterated shifts follows from measurability of `shift`.
@[measurability, fun_prop]
lemma shift_iterate_measurable (n : ℕ) :
    Measurable (shift^[n] : Ω[α] → Ω[α]) := by
  simpa using measurable_shift.iterate n

/-- A function that is pointwise shift-invariant and measurable is
    measurable with respect to the shift-invariant σ-algebra. -/
lemma shiftInvariant_implies_shiftInvariantMeasurable
    (g : Ω[α] → ℝ) (hg : Measurable g)
    (hinv : ∀ ω, g (shift ω) = g ω) :
    Measurable[shiftInvariantSigma] g := by
  intro t ht
  have hpreimage : MeasurableSet (g ⁻¹' t) := hg ht
  have hinv_preimage : shift ⁻¹' (g ⁻¹' t) = g ⁻¹' t := by
    ext ω
    simp [Set.mem_preimage, hinv ω]
  exact (mem_shiftInvariantSigma_iff (s:=g ⁻¹' t)).mpr ⟨hpreimage, hinv_preimage⟩

end Exchangeability.DeFinetti
