/-
Copyright (c) 2025 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Exchangeability.Probability.CondExp
import Exchangeability.DeFinetti.ViaMartingale.ShiftOperations
import Exchangeability.DeFinetti.ViaMartingale.RevFiltration

/-!
# Future Filtration

The future filtration at level m is σ(θ_{m+1} X), i.e., σ(X_{m+1}, X_{m+2}, ...).
This is the σ-algebra generated by coordinates after position m.

## Main definitions

* `futureFiltration X m` - σ(θ_{m+1} X) = σ(X_{m+1}, X_{m+2}, ...)
* `tailSigmaFuture X` - ⨅ m, futureFiltration X m (equals tailSigma X)

## Main results

* `futureFiltration_le` - futureFiltration is a sub-σ-algebra of the ambient
* `futureFiltration_antitone` - futureFiltration is decreasing in m
* `tailSigma_le_futureFiltration` - tail is coarser than any future filtration
* `tailSigmaFuture_eq_tailSigma` - the two tail definitions coincide

These are extracted from ViaMartingale.lean to enable modular imports.
-/

noncomputable section
open scoped MeasureTheory
open MeasureTheory

namespace Exchangeability.DeFinetti.ViaMartingale

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-! ### Future Filtration Definition -/

/-- Future reverse filtration: 𝔽ᶠᵘᵗₘ = σ(θ_{m+1} X). -/
abbrev futureFiltration (X : ℕ → Ω → α) (m : ℕ) : MeasurableSpace Ω :=
  MeasurableSpace.comap (shiftRV X (m + 1)) inferInstance

/-! ### Future Filtration Properties -/

section FutureFiltration

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

omit [MeasurableSpace Ω] in
/-- The future filtration is decreasing (antitone). -/
lemma futureFiltration_antitone (X : ℕ → Ω → α) :
    Antitone (futureFiltration X) := fun _ _ hmn =>
  revFiltration_antitone X (Nat.succ_le_succ hmn)

/-- Tail σ-algebra via the future filtration. (Additive alias.) -/
@[reducible] def tailSigmaFuture (X : ℕ → Ω → α) : MeasurableSpace Ω :=
  ⨅ m, futureFiltration X m

omit [MeasurableSpace Ω] in
@[simp] lemma tailSigmaFuture_eq_iInf (X : ℕ → Ω → α) :
    tailSigmaFuture X = ⨅ m, futureFiltration X m := rfl

omit [MeasurableSpace Ω] in
@[simp] lemma futureFiltration_eq_rev_succ (X : ℕ → Ω → α) (m : ℕ) :
    futureFiltration X m = revFiltration X (m + 1) := rfl

omit [MeasurableSpace Ω] in
lemma tailSigmaFuture_eq_tailSigma (X : ℕ → Ω → α) :
    tailSigmaFuture X = tailSigma X := by
  -- Both are infima of antitone sequences: ⨅ n, revFiltration X (n+1) vs ⨅ n, revFiltration X n
  -- These are equal because shifting by 1 doesn't change infimum of antitone sequence
  simp only [tailSigmaFuture, tailSigma, futureFiltration_eq_rev_succ]
  exact le_antisymm (iInf_mono fun n => revFiltration_antitone X (Nat.le_succ n))
    (le_iInf fun n => iInf_le _ (n + 1))

/-! ### Helper lemmas for tail σ-algebra -/

/-- The tail σ-algebra is a sub-σ-algebra of the ambient σ-algebra. -/
lemma tailSigma_le {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    (X : ℕ → Ω → α) (hX : ∀ n, Measurable (X n)) :
    tailSigma X ≤ (inferInstance : MeasurableSpace Ω) :=
  iInf_le_of_le 0 (revFiltration_le X hX 0)

/-- Tail σ-algebra is sub-σ-algebra of future filtration. -/
@[nolint unusedArguments]
lemma tailSigma_le_futureFiltration {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    (X : ℕ → Ω → α) (m : ℕ) :
    tailSigma X ≤ futureFiltration X m :=
  iInf_le_of_le (m + 1) le_rfl

/-! ### Helper lemmas for futureFiltration properties -/

/-- Future filtration is sub-σ-algebra of ambient. -/
lemma futureFiltration_le {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    (X : ℕ → Ω → α) (m : ℕ) (hX : ∀ n, Measurable (X n)) :
    futureFiltration X m ≤ (inferInstance : MeasurableSpace Ω) :=
  revFiltration_le X hX (m + 1)

end FutureFiltration

end Exchangeability.DeFinetti.ViaMartingale
