/-
Copyright (c) 2025 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Exchangeability.Tail.TailSigma
import Exchangeability.DeFinetti.MartingaleHelpers
import Exchangeability.DeFinetti.ViaMartingale.ShiftOperations

/-!
# Reverse Filtration and Tail σ-Algebra

This file defines the reverse filtration (decreasing σ-algebras generated by shifts)
and the tail σ-algebra (their intersection).

## Main definitions

* `revFiltration X m` - σ(θₘ X) = σ(ω ↦ (n ↦ X (m+n) ω))
* `tailSigma X` - ⋂ₙ σ(Xₙ, Xₙ₊₁, ...), the tail σ-algebra

## Main results

* `revFiltration_le` - revFiltration is a sub-σ-algebra of the ambient
* `revFiltration_antitone` - revFiltration is decreasing in m
* `tailSigma_eq_canonical` - matches `Tail.tailProcess`

These are extracted from ViaMartingale.lean to enable modular imports.
-/

noncomputable section
open scoped MeasureTheory
open MeasureTheory

namespace Exchangeability.DeFinetti.ViaMartingale

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

open MartingaleHelpers

/-! ### Reverse Filtration -/

/-- 𝔽ₘ := σ(θₘ X) = σ(ω ↦ (n ↦ X (m+n) ω)). -/
abbrev revFiltration (X : ℕ → Ω → α) (m : ℕ) : MeasurableSpace Ω :=
  MeasurableSpace.comap (shiftRV X m) inferInstance

lemma revFiltration_le (X : ℕ → Ω → α) (hX : ∀ n, Measurable (X n)) (m : ℕ) :
    revFiltration X m ≤ (inferInstance : MeasurableSpace Ω) :=
  by
    simpa [revFiltration] using (measurable_iff_comap_le.mp (measurable_shiftRV (X := X) hX (m := m)))

/-! ### Tail σ-Algebra -/

/-- The tail σ-algebra for a process X: ⋂ₙ σ(Xₙ, Xₙ₊₁, ...). -/
@[reducible] def tailSigma (X : ℕ → Ω → α) : MeasurableSpace Ω :=
  ⨅ m, revFiltration X m

omit [MeasurableSpace Ω] in
@[simp]
lemma tailSigma_eq_iInf_rev (X : ℕ → Ω → α) :
    tailSigma X = ⨅ m, revFiltration X m := rfl

omit [MeasurableSpace Ω] in
/-- Bridge to canonical tail definition: ViaMartingale's `revFiltration` matches the pattern
    required by `Tail.tailProcess_eq_iInf_revFiltration`. -/
lemma revFiltration_eq_tailFamily (X : ℕ → Ω → α) (m : ℕ) :
    revFiltration X m =
    ⨆ k : ℕ, MeasurableSpace.comap (fun ω => X (m + k) ω) inferInstance := by
  -- Unfold revFiltration: σ(shiftRV X m) = σ(ω ↦ (n ↦ X(m+n) ω))
  simp only [revFiltration]
  -- The product σ-algebra on (ℕ → α) equals ⨆ k, σ(eval_k)
  conv_lhs => rw [show (inferInstance : MeasurableSpace (ℕ → α)) = MeasurableSpace.pi from rfl]
  -- Expand pi as supremum of coordinate comaps
  rw [show MeasurableSpace.pi = ⨆ k, MeasurableSpace.comap (fun f : ℕ → α => f k) inferInstance from rfl]
  -- Push comap through supremum: comap f (⨆ σᵢ) = ⨆ comap f σᵢ
  rw [MeasurableSpace.comap_iSup]
  -- Simplify: comap (shiftRV X m) (comap eval_k) = comap (eval_k ∘ shiftRV X m)
  congr 1; funext k; rw [MeasurableSpace.comap_comp]; rfl

omit [MeasurableSpace Ω] in
/-- ViaMartingale's `tailSigma` equals the canonical `Tail.tailProcess`. -/
lemma tailSigma_eq_canonical (X : ℕ → Ω → α) :
    tailSigma X = Exchangeability.Tail.tailProcess X := by
  unfold tailSigma
  exact (Exchangeability.Tail.tailProcess_eq_iInf_revFiltration X revFiltration (revFiltration_eq_tailFamily X)).symm

/-! ### Monotonicity -/

omit [MeasurableSpace Ω] in
lemma revFiltration_antitone (X : ℕ → Ω → α) :
    Antitone (revFiltration X) := by
  intro m n hmn
  -- Need to show: revFiltration X n ≤ revFiltration X m when m ≤ n
  -- Strategy: shiftRV X n = shiftSeq (n - m) ∘ shiftRV X m
  simp only [revFiltration]
  let k := n - m
  -- Show shiftRV X n = shiftSeq k ∘ shiftRV X m
  have h_comp : shiftRV X n = shiftSeq k ∘ shiftRV X m := by
    funext ω i
    simp only [shiftRV, shiftSeq, Function.comp_apply]
    congr 1
    omega
  rw [h_comp, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono measurable_shiftSeq.comap_le

end Exchangeability.DeFinetti.ViaMartingale
