/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.Constructions.Pi
import Mathlib.MeasureTheory.PiSystem
import Mathlib.Probability.Kernel.Basic

/-!
# Measurability of Product Measure Kernels

This file contains technical lemmas about measurability of product measure kernels.
These lemmas support de Finetti-type theorems but are general-purpose results about
measure theory on product spaces.

## Main Results

* `measurable_prod_ennreal`: Products of measurable ENNReal functions are measurable
* `rectangles_isPiSystem`: Measurable rectangles form a π-system
* `rectangles_generate_pi_sigma`: Product σ-algebra = generateFrom of rectangles
* `measurable_measure_pi`: Measurability of product measure kernels ω ↦ ∏ᵢ ν ω

## Mathematical Context

The key technique is π-system induction: proving measurability on rectangles (a π-system)
and extending to all measurable sets via the π-λ theorem.

## Suggested Mathlib Location

`Mathlib.Probability.Kernel.Measurable` or `Mathlib.MeasureTheory.Constructions.Pi`

## References

* Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*
-/

noncomputable section
open scoped BigOperators MeasureTheory
open MeasureTheory ProbabilityTheory Set

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-! ### Preliminary lemmas -/

/-- The product of finitely many measurable ENNReal-valued functions is measurable.

This is a wrapper around `Finset.measurable_prod` specialized to ENNReal. -/
lemma measurable_prod_ennreal {ι : Type*} [Fintype ι] {Ω : Type*} [MeasurableSpace Ω]
    (f : ι → Ω → ENNReal) (hf : ∀ i, Measurable (f i)) :
    Measurable fun ω => ∏ i, f i ω :=
  Finset.measurable_prod _ fun i _ => hf i

/-- Rewrite `Set.univ.pi B` as a setOf comprehension. -/
lemma univ_pi_eq_setOf_forall {ι : Type*} {α : Type*} (B : ι → Set α) :
    Set.univ.pi B = {x | ∀ i, x i ∈ B i} := by
  ext x; simp [Set.pi]

/-! ### π-system structure of rectangles -/

/-- Measurable rectangles form a π-system for the product σ-algebra.

A rectangle in (Fin m → α) is a set of the form {x | ∀ i, x i ∈ B i} where each B i
is measurable. The collection of such rectangles is closed under finite intersections. -/
lemma rectangles_isPiSystem {m : ℕ} {α : Type*} [MeasurableSpace α] :
    IsPiSystem {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} := by
  intro S₁ hS₁ S₂ hS₂ _hne
  obtain ⟨B₁, hB₁_meas, rfl⟩ := hS₁
  obtain ⟨B₂, hB₂_meas, rfl⟩ := hS₂
  use fun i => B₁ i ∩ B₂ i
  constructor
  · exact fun i => (hB₁_meas i).inter (hB₂_meas i)
  · ext x
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
    exact ⟨fun ⟨h₁, h₂⟩ i => ⟨h₁ i, h₂ i⟩, fun h => ⟨fun i => (h i).1, fun i => (h i).2⟩⟩

/-- The product σ-algebra on (Fin m → α) is generated by measurable rectangles.

This is a fundamental result in product measure theory: the σ-algebra on a finite
product equals the σ-algebra generated by measurable rectangles. -/
lemma rectangles_generate_pi_sigma {m : ℕ} {α : Type*} [MeasurableSpace α] :
    (inferInstance : MeasurableSpace (Fin m → α)) =
    MeasurableSpace.generateFrom {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} := by
  have set_eq : {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} =
      Set.pi univ '' Set.pi univ fun i : Fin m => {s : Set α | MeasurableSet s} := by
    ext S
    constructor
    · intro ⟨B, hB_meas, hS⟩
      use fun i => B i
      simp only [Set.mem_pi]
      exact ⟨fun i _ => hB_meas i, by rw [univ_pi_eq_setOf_forall]; exact hS.symm⟩
    · intro ⟨B, hB_mem, hS⟩
      simp only [Set.mem_pi, Set.mem_univ, Set.mem_setOf_eq] at hB_mem hS
      use B
      exact ⟨fun i => hB_mem i (Set.mem_univ i), by rw [← univ_pi_eq_setOf_forall]; exact hS.symm⟩
  rw [set_eq]
  exact generateFrom_pi.symm

/-! ### Measurability of product measure kernels -/

/-- The product measure kernel ω ↦ Measure.pi (fun _ => ν ω) is measurable.

Given a measurable family of probability measures ν : Ω → Measure α, the product
kernel ω ↦ ∏ᵢ ν ω (where i ranges over Fin m) is measurable as a measure-valued map.

**Proof strategy**: Use π-system induction on rectangles:
1. Rectangles generate the product σ-algebra (`rectangles_generate_pi_sigma`)
2. Rectangles form a π-system (`rectangles_isPiSystem`)
3. On rectangles, the product measure of {x | ∀ i, x i ∈ B i} equals ∏ᵢ ν ω (B i),
   which is measurable in ω by `measurable_prod_ennreal`
4. By the π-λ theorem, measurability on the generating π-system extends to all measurable sets

This is a key lemma for proving the ConditionallyIID property in de Finetti's theorem. -/
lemma measurable_measure_pi {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    {m : ℕ}
    (ν : Ω → Measure α) (hν_prob : ∀ ω, IsProbabilityMeasure (ν ω))
    (hν_meas : ∀ s, MeasurableSet s → Measurable (fun ω => ν ω s)) :
    Measurable fun ω => Measure.pi fun _ : Fin m => ν ω := by
  classical
  let κ : Ω → Measure (Fin m → α) := fun ω => Measure.pi fun _ : Fin m => ν ω
  let 𝒞 : Set (Set (Fin m → α)) :=
    {S | ∃ (B : Fin m → Set α), (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}}

  have h_gen : (inferInstance : MeasurableSpace (Fin m → α)) = MeasurableSpace.generateFrom 𝒞 :=
    rectangles_generate_pi_sigma (m := m) (α := α)
  have h_pi : IsPiSystem 𝒞 := rectangles_isPiSystem (m := m) (α := α)

  -- Values on rectangles are measurable
  have h_basic : ∀ t ∈ 𝒞, Measurable fun ω => κ ω t := by
    intro t ht
    rcases ht with ⟨B, hB, rfl⟩
    have rect : (fun ω => κ ω {x : Fin m → α | ∀ i, x i ∈ B i}) = fun ω => ∏ i : Fin m, ν ω (B i) :=
      by funext ω
         have : {x : Fin m → α | ∀ i, x i ∈ B i} = Set.univ.pi B := by ext; simp [Set.pi]
         simp only [κ, this, Measure.pi_pi]
    have hmeas : Measurable fun ω => ∏ i : Fin m, ν ω (B i) :=
      measurable_prod_ennreal (fun i ω => ν ω (B i)) (fun i => hν_meas (B i) (hB i))
    simpa [κ, rect]

  -- Each product measure is a probability measure
  haveI hκ_prob : ∀ ω, IsProbabilityMeasure (κ ω) := by
    intro ω
    haveI : ∀ i : Fin m, IsProbabilityMeasure (ν ω) := fun _ => hν_prob ω
    infer_instance

  -- Apply π-λ theorem
  exact Measurable.measure_of_isPiSystem_of_isProbabilityMeasure h_gen h_pi h_basic

