/-
Copyright (c) 2025 leantest-afp contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: leantest-afp contributors
-/
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.InnerProductSpace.Projection.Basic
import LeantestAfp.Probability.Ergodic.KoopmanMeanErgodic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondexpL2

/-!
# Shift-invariant σ-algebra and conditional expectation

This file defines the shift-invariant σ-algebra on path space and establishes
the fundamental connection between:
- The fixed-point subspace of the Koopman operator
- The L² space with respect to the shift-invariant σ-algebra
- The conditional expectation onto the shift-invariant σ-algebra

## Main definitions

* `isShiftInvariant`: Predicate for sets that are invariant under the shift map.
* `shiftInvariantSigma`: The σ-algebra of shift-invariant sets.
* `fixedSubspace`: The subspace of L² functions fixed by the Koopman operator.

## Main results

* `mem_shiftInvariantSigma_iff`: Characterization of membership in the invariant σ-algebra.
* `fixedSpace_eq_invMeasurable`: Functions fixed by Koopman are exactly those
  measurable with respect to the shift-invariant σ-algebra.
* `proj_eq_condexp`: The orthogonal projection onto the fixed-point subspace equals
  the conditional expectation onto the shift-invariant σ-algebra.

## References

* Olav Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*,
  Springer, Chapter 1 (pages 26-27). The shift-invariant σ-algebra is denoted
  𝓘_ξ in Kallenberg.

-/

noncomputable section

open scoped Classical

namespace LeantestAfp.Probability.DeFinetti

open MeasureTheory Filter Topology
open LeantestAfp.Probability.Ergodic

variable {α : Type*} [MeasurableSpace α]

/-- A set is shift-invariant if it is measurable and equals its preimage under shift. -/
def isShiftInvariant (s : Set (Ω[α])) : Prop :=
  MeasurableSet s ∧ shift ⁻¹' s = s

lemma isShiftInvariant_iff (s : Set (Ω[α])) :
    isShiftInvariant s ↔ MeasurableSet s ∧ ∀ ω, shift ω ∈ s ↔ ω ∈ s := by
  constructor
  · intro ⟨hm, heq⟩
    exact ⟨hm, fun ω => by rw [← Set.mem_preimage, heq]⟩
  · intro ⟨hm, hiff⟩
    refine ⟨hm, Set.ext fun ω => ?_⟩
    simp [hiff]

/-- The shift-invariant σ-algebra: the collection of shift-invariant sets.

For now we define this axiomatically; a full construction would use the σ-algebra
generated by shift-invariant sets or the comap construction.
-/
def shiftInvariantSigma : MeasurableSpace (Ω[α]) where
  MeasurableSet' := fun s => isShiftInvariant (α := α) s
  measurableSet_empty := by
    refine ⟨measurableSet_empty, ?_⟩
    simp
  measurableSet_compl := by
    intro s hs
    obtain ⟨hs_meas, hs_eq⟩ := hs
    refine ⟨hs_meas.compl, ?_⟩
    simpa [Set.preimage_compl, hs_eq, Set.compl_compl]
  measurableSet_iUnion := by
    intro f hf
    refine ⟨measurableSet_iUnion fun n => (hf n).left, ?_⟩
    ext ω
    simp [Set.preimage_iUnion, hf]

lemma shiftInvariantSigma_le :
    shiftInvariantSigma ≤ (inferInstance : MeasurableSpace (Ω[α])) := by
  intro s hs
  exact (hs : isShiftInvariant (α := α) s).1

lemma mem_shiftInvariantSigma_iff (s : Set (Ω[α])) :
    @MeasurableSet _ shiftInvariantSigma s ↔ isShiftInvariant (α := α) s :=
  Iff.rfl

/-- Shift-invariant measurability forces pointwise invariance under the shift map. -/
lemma shiftInvariantSigma_measurable_shift_eq
    (g : Ω[α] → ℝ)
    (hg : @Measurable _ shiftInvariantSigma _ g) :
    (fun ω => g (shift ω)) = g := by
  classical
  ext ω
  by_contra hneq
  have hlt_or := lt_or_gt_of_ne hneq
  cases' hlt_or with hlt hgt
  · -- Case `g (shift ω) < g ω`
    obtain ⟨q, hltq, hqω⟩ := exists_rat_btwn hlt
    have hset_eq := (hg (MeasurableSet_Iio (q : ℝ))).2
    have h_shift_mem : shift ω ∈ g ⁻¹' Set.Iio (q : ℝ) := by
      simpa [Set.mem_preimage] using hltq
    have h_pre : ω ∈ shift ⁻¹' (g ⁻¹' Set.Iio (q : ℝ)) := by
      simpa [Set.mem_preimage] using h_shift_mem
    have h_mem : ω ∈ g ⁻¹' Set.Iio (q : ℝ) := by
      simpa [hset_eq] using h_pre
    have : g ω < (q : ℝ) := by
      simpa [Set.mem_preimage] using h_mem
    have : g ω < g ω := lt_trans this hqω
    exact lt_irrefl _ this
  · -- Case `g ω < g (shift ω)`
    obtain ⟨q, hωq, hq_lt⟩ := exists_rat_btwn hgt
    have hset_eq := (hg (MeasurableSet_Ioi (q : ℝ))).2
    have h_shift_mem : shift ω ∈ g ⁻¹' Set.Ioi (q : ℝ) := by
      simpa [Set.mem_preimage] using hq_lt
    have h_pre : ω ∈ shift ⁻¹' (g ⁻¹' Set.Ioi (q : ℝ)) := by
      simpa [Set.mem_preimage] using h_shift_mem
    have h_mem : ω ∈ g ⁻¹' Set.Ioi (q : ℝ) := by
      simpa [hset_eq] using h_pre
    have : (q : ℝ) < g ω := by
      simpa [Set.mem_preimage] using h_mem
    have : g ω < g ω := lt_trans hωq this
    exact lt_irrefl _ this

/-- A function is measurable with respect to the shift-invariant σ-algebra iff
it is (a.e.) constant along shift orbits. -/
lemma invMeasurable_iff_shiftInvariant {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (_hσ : MeasurePreserving shift μ μ) (g : Ω[α] → ℝ) :
    (∀ᵐ ω ∂μ, g (shift ω) = g ω) →
    (@Measurable _ _ shiftInvariantSigma _ g →
     ∀ᵐ ω ∂μ, g (shift ω) = g ω) := by
  intro _ hmeas
  refine eventually_of_forall ?_
  intro ω
  have hfun := congrArg (fun f => f ω) (shiftInvariantSigma_measurable_shift_eq g hmeas)
  simpa using hfun

/-- Functions that are `AEStronglyMeasurable` with respect to the invariant σ-algebra are
almost everywhere fixed by the shift. -/
lemma shiftInvariantSigma_aestronglyMeasurable_ae_shift_eq
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) {f : Ω[α] → ℝ}
    (hf : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ) :
    (fun ω => f (shift ω)) =ᵐ[μ] f := by
  classical
  rcases hf with ⟨g, hg_meas, hfg⟩
  have hcomp :=
    (hσ.quasiMeasurePreserving).ae_eq_comp (μ := μ) (ν := μ)
      (f := shift (α := α)) (g := fun ω => f ω) (g' := fun ω => g ω) hfg
  have hshift : (fun ω => g (shift ω)) =ᵐ[μ] g :=
    EventuallyEq.of_eq (shiftInvariantSigma_measurable_shift_eq g hg_meas.measurable)
  exact hcomp.trans <| hshift.trans hfg.symm

/-- If an `Lp` function is measurable with respect to the invariant σ-algebra, the Koopman
operator fixes it. -/
lemma koopman_eq_self_of_shiftInvariant
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    {f : Lp ℝ 2 μ}
    (hf : AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ) :
    koopman shift hσ f = f := by
  classical
  have hcomp :
      (koopman shift hσ f) =ᵐ[μ]
        (fun ω => f (shift ω)) := by
    change MeasureTheory.Lp.compMeasurePreserving (shift (α := α)) hσ f =ᵐ[μ]
        fun ω => f (shift ω)
    simpa [koopman]
      using
        (MeasureTheory.Lp.coeFn_compMeasurePreserving (μ := μ) (μb := μ)
            (p := (2 : ℝ≥0∞)) f hσ)
  have hshift := shiftInvariantSigma_aestronglyMeasurable_ae_shift_eq (μ := μ) hσ hf
  have hfinal : (koopman shift hσ f) =ᵐ[μ] f := hcomp.trans hshift
  exact Lp.ext hfinal

/-- A Koopman-fixed function should be measurable with respect to the invariant σ-algebra.

The key step is to modify a representative of `f` on a null set so that it becomes
pointwise invariant under the shift; the resulting function will then be
`shiftInvariantSigma`-measurable by construction. -/
lemma aestronglyMeasurable_shiftInvariant_of_koopman
    {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ)
    {f : Lp ℝ 2 μ}
    (hfix : koopman shift hσ f = f) :
    AEStronglyMeasurable[shiftInvariantSigma (α := α)] f μ := by
  classical
  /-
  Proof strategy sketch:
  1. Unfold the equality `koopman shift hσ f = f` to obtain the almost-everywhere
     identity `(fun ω => f (shift ω)) =ᵐ[μ] f`.
  2. Choose a strongly measurable representative `g` of `f`.
  3. Modify `g` on the μ-null set where the shift invariance fails to build a
     pointwise invariant function `g'` with `g' = g` almost everywhere.
  4. Perform the null-set modification inductively along the orbit to ensure
     `g' ∘ shift = g'` on the nose.
  5. Conclude that the preimage of any Borel set under `g'` is shift-invariant,
     hence belongs to `shiftInvariantSigma` by definition, giving the desired
     measurability.
  6. Finally transport this back to the original `f` using the `AE` equality.

  Implementing steps (3)–(5) will likely require a bespoke lemma about
  modifying functions on null sets to enforce invariance; this will be filled in
  later.
  -/
  -- STEP 1. Extract the a.e. invariance statement from `koopman` equality.
  have hshift : (fun ω => f (shift ω)) =ᵐ[μ] f := by
    have := congrArg (fun g : Lp ℝ 2 μ => g) hfix
    exact this
  -- STEP 2. Choose a strongly measurable representative of `f`.
  have hf_base : AEStronglyMeasurable f μ := by
    simpa using (Lp.aestronglyMeasurable (μ := μ) (p := (2 : ℝ≥0∞)) f)
  obtain ⟨g, hg_meas, hfg⟩ := hf_base
  -- Transport the a.e. invariance to the chosen representative.
  have hshift_g : (fun ω => g (shift ω)) =ᵐ[μ] g := by
    have hcomp := (hσ.quasiMeasurePreserving.ae_eq_comp hfg)
    have hcomp' : (fun ω => g (shift ω)) =ᵐ[μ] (fun ω => f (shift ω)) := by
      simpa using hcomp
    have hshift' : (fun ω => f (shift ω)) =ᵐ[μ] g := hshift.trans hfg
    exact hcomp'.trans hshift'
  -- STEP 3. Record the full-measure set on which the representative is pointwise invariant.
  let S : Set (Ω[α]) := {ω | g (shift ω) = g ω}
  have hS_ae : ∀ᵐ ω ∂μ, ω ∈ S := by
    simpa [S, Set.mem_setOf_eq] using hshift_g
  have hS_null : μ Sᶜ = 0 := by
    simpa [ae_iff, S, Set.mem_setOf_eq] using hS_ae
  -- TODO: Define `S∞ := ⋂ n, (shift^[n]) ⁻¹' S` and prove it has full μ-measure using the
  -- measure-preserving property of the iterates of `shift`.
  -- TODO: show that `S` is measurable and construct the iterated invariant set `S∞`.
  -- TODO: Continue by modifying a representative of `f` on a null set to obtain a pointwise
  -- shift-invariant function and use it to show `f` is measurable w.r.t. `shiftInvariantSigma`.
  sorry

/-- The fixed-point subspace of the Koopman operator.

This is the closed subspace of L²(μ) consisting of equivalence classes of functions
f such that f ∘ shift = f almost everywhere.
-/
def fixedSubspace {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) : Submodule ℝ (Lp ℝ 2 μ) :=
  fixedSpace (koopman shift hσ)

/-- Functions in the fixed-point subspace are exactly those that are a.e. invariant under shift. -/
lemma mem_fixedSubspace_iff {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) (f : Lp ℝ 2 μ) :
    f ∈ fixedSubspace hσ ↔ koopman shift hσ f = f := by
  rfl

/-- The orthogonal projection onto the fixed-point subspace exists (as a closed subspace). -/
lemma fixedSubspace_closed {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    IsClosed (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := by
  classical
  let T := koopman shift hσ
  have hset : (fixedSubspace hσ : Set (Lp ℝ 2 μ)) =
      (fun f : Lp ℝ 2 μ => T f - f) ⁻¹' ({0} : Set (Lp ℝ 2 μ)) := by
    ext f
    rfl
  have hcont : Continuous fun f : Lp ℝ 2 μ => T f - f :=
    (T.continuous.sub continuous_id)
  have hclosed : IsClosed ((fun f : Lp ℝ 2 μ => T f - f) ⁻¹'
      ({0} : Set (Lp ℝ 2 μ))) :=
    IsClosed.preimage hcont isClosed_singleton
  simpa [hset]

/-- Conditional expectation on L² can be viewed as an orthogonal projection.

For a sub-σ-algebra 𝓖, the conditional expectation condexp[𝓖] is the orthogonal
projection from L²(μ) onto L²(𝓖), the closed subspace of functions measurable
with respect to 𝓖.

TODO: Use mathlib's condexpL2 once we have the proper sub-σ-algebra instance.
-/
noncomputable def condexpL2 {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] :
    Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  ((lpMeas ℝ ℝ (shiftInvariantSigma (α := α)) 2 μ).subtypeL).comp
    (MeasureTheory.condExpL2 ℝ ℝ (shiftInvariantSigma_le (α := α)))

/-- Key theorem: The orthogonal projection onto the fixed-point subspace of the Koopman
operator equals the conditional expectation onto the shift-invariant σ-algebra.

This is the bridge between ergodic theory (operator fixed points) and probability
(conditional expectation).
-/
theorem proj_eq_condexp {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    ∃ (P : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ),
      (∀ f, f ∈ fixedSubspace hσ → P f = f) ∧
      (∀ f, P f = condexpL2 shiftInvariantSigma f) := by
  /-
  Sketch of proof:
  1. Let `P₀ := (lpMeas …).orthogonalProjection`. Observe that our definition of `condexpL2`
     is `subtypeL.comp P₀`, so showing `P₀` equals the orthogonal projection onto
     `fixedSubspace hσ` is enough.
  2. Build the equivalence of subspaces.
     * (Forward) If `g` is `shiftInvariantSigma`-measurable, then `g ∘ shift = g` a.e.
       Produce a lemma
         `lemma shiftInvariantSigma_measurable_aestronglyMeasurable
             (hg : AEStronglyMeasurable[m] g μ) : g ∘ shift =ᵐ μ g`.
       This will use that measurable sets in `shiftInvariantSigma` are invariant by the
       definition of the σ-algebra, together with the fact that evaluation maps on `Ω[α]`
       generate the σ-algebra.
     * (Reverse) If `koopman shift hσ f = f`, then `f` is invariant a.e.  Use the
       representatives lemma for `Lp` to get an a.e. equal function `g`. Show that `g` is
       measurable w.r.t. `shiftInvariantSigma` by proving that its level sets belong to
       the invariant σ-algebra.  A convenient way is to start with simple functions,
       use stability of the invariant σ-algebra under limits, and appeal to the
       dominated convergence theorem.
  3. Once the two closed subspaces agree, uniqueness of orthogonal projections yields the
     desired statement (cf. `Submodule.orthogonalProjection_eq_self_of_subset`).
  4. Finally, wrap up: choose `P := condexpL2 shiftInvariantSigma` and show it satisfies the
     two characterising properties using the two inclusions from step 2.
  -/
  sorry

/-- The range of conditional expectation onto the invariant σ-algebra equals
the fixed-point subspace. -/
lemma range_condexp_eq_fixedSubspace {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    Set.range (condexpL2 shiftInvariantSigma) =
    (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := by
  classical
  ext f
  constructor
  · -- (⊆) Range of condexpL2 ⊆ fixedSubspace
    intro ⟨g, hg⟩
    rw [← hg]
    -- condexpL2 g is measurable w.r.t. shiftInvariantSigma
    -- hence invariant under shift, so Koopman fixes it
    classical
    have hmeas :
        AEStronglyMeasurable[shiftInvariantSigma (α := α)]
          (condexpL2 shiftInvariantSigma g : Ω[α] → ℝ) μ := by
      simpa using
        (lpMeas.aestronglyMeasurable
          (MeasureTheory.condExpL2 ℝ ℝ (shiftInvariantSigma_le (α := α)) g))
    have hkoop :=
      koopman_eq_self_of_shiftInvariant (hσ := hσ) hmeas
    exact (mem_fixedSubspace_iff (hσ := hσ)
        (f := condexpL2 shiftInvariantSigma g)).mpr hkoop
  · -- (⊇) fixedSubspace ⊆ Range of condexpL2
    intro hf
    -- If f is fixed by Koopman, then f is shift-invariant a.e.
    -- hence measurable w.r.t. shiftInvariantSigma
    -- so f = condexpL2 f
    use f
    /-
    Outline:
    1. Starting from `hf : f ∈ fixedSubspace hσ`, use `mem_fixedSubspace_iff` to get the
       almost everywhere invariance of `f` under `shift`.
    2. Produce a representative that is strictly invariant on a μ-a.e. invariant set,
       then prove it is `shiftInvariantSigma`-measurable (reverse inclusion lemma).
    3. Invoke the defining property of conditional expectation on `Lp` to conclude that
       `condexpL2 shiftInvariantSigma f = f`.
    -/
    sorry

end LeantestAfp.Probability.DeFinetti
