/-
Copyright (c) 2025 leantest-afp contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: leantest-afp contributors
-/
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.InnerProductSpace.Projection.Basic
import LeantestAfp.Probability.Ergodic.KoopmanMeanErgodic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondexpL2

/-!
# Shift-invariant σ-algebra and conditional expectation

This file defines the shift-invariant σ-algebra on path space and establishes
the fundamental connection between:
- The fixed-point subspace of the Koopman operator
- The L² space with respect to the shift-invariant σ-algebra
- The conditional expectation onto the shift-invariant σ-algebra

## Main definitions

* `isShiftInvariant`: Predicate for sets that are invariant under the shift map.
* `shiftInvariantSigma`: The σ-algebra of shift-invariant sets.
* `fixedSubspace`: The subspace of L² functions fixed by the Koopman operator.

## Main results

* `mem_shiftInvariantSigma_iff`: Characterization of membership in the invariant σ-algebra.
* `fixedSpace_eq_invMeasurable`: Functions fixed by Koopman are exactly those
  measurable with respect to the shift-invariant σ-algebra.
* `proj_eq_condexp`: The orthogonal projection onto the fixed-point subspace equals
  the conditional expectation onto the shift-invariant σ-algebra.

## References

* Olav Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*,
  Springer, Chapter 1 (pages 26-27). The shift-invariant σ-algebra is denoted
  𝓘_ξ in Kallenberg.

-/

noncomputable section

open scoped Classical

namespace LeantestAfp.Probability.DeFinetti

open MeasureTheory Filter Topology
open LeantestAfp.Probability.Ergodic

variable {α : Type*} [MeasurableSpace α]

/-- A set is shift-invariant if it is measurable and equals its preimage under shift. -/
def isShiftInvariant (s : Set (Ω[α])) : Prop :=
  MeasurableSet s ∧ shift ⁻¹' s = s

lemma isShiftInvariant_iff (s : Set (Ω[α])) :
    isShiftInvariant s ↔ MeasurableSet s ∧ ∀ ω, shift ω ∈ s ↔ ω ∈ s := by
  constructor
  · intro ⟨hm, heq⟩
    exact ⟨hm, fun ω => by rw [← Set.mem_preimage, heq]⟩
  · intro ⟨hm, hiff⟩
    refine ⟨hm, Set.ext fun ω => ?_⟩
    simp [hiff]

/-- The shift-invariant σ-algebra: the collection of shift-invariant sets.

For now we define this axiomatically; a full construction would use the σ-algebra
generated by shift-invariant sets or the comap construction.
-/
def shiftInvariantSigma : MeasurableSpace (Ω[α]) where
  MeasurableSet' := fun s => isShiftInvariant (α := α) s
  measurableSet_empty := by
    refine ⟨measurableSet_empty, ?_⟩
    simp
  measurableSet_compl := by
    intro s hs
    obtain ⟨hs_meas, hs_eq⟩ := hs
    refine ⟨hs_meas.compl, ?_⟩
    simpa [Set.preimage_compl, hs_eq, Set.compl_compl]
  measurableSet_iUnion := by
    intro f hf
    refine ⟨measurableSet_iUnion fun n => (hf n).left, ?_⟩
    ext ω
    simp [Set.preimage_iUnion, hf]

lemma shiftInvariantSigma_le :
    shiftInvariantSigma ≤ (inferInstance : MeasurableSpace (Ω[α])) := by
  intro s hs
  exact (hs : isShiftInvariant (α := α) s).1

lemma mem_shiftInvariantSigma_iff (s : Set (Ω[α])) :
    @MeasurableSet _ shiftInvariantSigma s ↔ isShiftInvariant (α := α) s :=
  Iff.rfl

/-- A function is measurable with respect to the shift-invariant σ-algebra iff
it is (a.e.) constant along shift orbits. -/
lemma invMeasurable_iff_shiftInvariant {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (_hσ : MeasurePreserving shift μ μ) (g : Ω[α] → ℝ) :
    (∀ᵐ ω ∂μ, g (shift ω) = g ω) →
    (@Measurable _ _ shiftInvariantSigma _ g →
     ∀ᵐ ω ∂μ, g (shift ω) = g ω) := by
  intro hinv _
  exact hinv

/-- The fixed-point subspace of the Koopman operator.

This is the closed subspace of L²(μ) consisting of equivalence classes of functions
f such that f ∘ shift = f almost everywhere.
-/
def fixedSubspace {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) : Submodule ℝ (Lp ℝ 2 μ) :=
  fixedSpace (koopman shift hσ)

/-- Functions in the fixed-point subspace are exactly those that are a.e. invariant under shift. -/
lemma mem_fixedSubspace_iff {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) (f : Lp ℝ 2 μ) :
    f ∈ fixedSubspace hσ ↔ koopman shift hσ f = f := by
  rfl

/-- The orthogonal projection onto the fixed-point subspace exists (as a closed subspace). -/
lemma fixedSubspace_closed {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    IsClosed (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := by
  classical
  let T := koopman shift hσ
  have hset : (fixedSubspace hσ : Set (Lp ℝ 2 μ)) =
      (fun f : Lp ℝ 2 μ => T f - f) ⁻¹' ({0} : Set (Lp ℝ 2 μ)) := by
    ext f
    rfl
  have hcont : Continuous fun f : Lp ℝ 2 μ => T f - f :=
    (T.continuous.sub continuous_id)
  have hclosed : IsClosed ((fun f : Lp ℝ 2 μ => T f - f) ⁻¹'
      ({0} : Set (Lp ℝ 2 μ))) :=
    IsClosed.preimage hcont isClosed_singleton
  simpa [hset]

/-- Conditional expectation on L² can be viewed as an orthogonal projection.

For a sub-σ-algebra 𝓖, the conditional expectation condexp[𝓖] is the orthogonal
projection from L²(μ) onto L²(𝓖), the closed subspace of functions measurable
with respect to 𝓖.

TODO: Use mathlib's condexpL2 once we have the proper sub-σ-algebra instance.
-/
noncomputable def condexpL2 {μ : Measure (Ω[α])} [IsProbabilityMeasure μ] :
    Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  ((lpMeas ℝ ℝ (shiftInvariantSigma (α := α)) 2 μ).subtypeL).comp
    (MeasureTheory.condExpL2 ℝ ℝ (shiftInvariantSigma_le (α := α)))

/-- Key theorem: The orthogonal projection onto the fixed-point subspace of the Koopman
operator equals the conditional expectation onto the shift-invariant σ-algebra.

This is the bridge between ergodic theory (operator fixed points) and probability
(conditional expectation).
-/
theorem proj_eq_condexp {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    ∃ (P : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ),
      (∀ f, f ∈ fixedSubspace hσ → P f = f) ∧
      (∀ f, P f = condexpL2 shiftInvariantSigma f) := by
  sorry
  -- Proof outline:
  -- 1. Both operators are orthogonal projections onto closed subspaces
  -- 2. Show the target subspaces are equal:
  --    (a) If f is shiftInvariantSigma-measurable, then koopman shift hσ f = f
  --    (b) If koopman shift hσ f = f, then f is a.e. measurable w.r.t. shiftInvariantSigma
  -- 3. Orthogonal projections onto the same closed subspace are unique

/-- The range of conditional expectation onto the invariant σ-algebra equals
the fixed-point subspace. -/
lemma range_condexp_eq_fixedSubspace {μ : Measure (Ω[α])} [IsProbabilityMeasure μ]
    (hσ : MeasurePreserving shift μ μ) :
    Set.range (condexpL2 shiftInvariantSigma) =
    (fixedSubspace hσ : Set (Lp ℝ 2 μ)) := by
  classical
  ext f
  constructor
  · -- (⊆) Range of condexpL2 ⊆ fixedSubspace
    intro ⟨g, hg⟩
    rw [← hg]
    -- condexpL2 g is measurable w.r.t. shiftInvariantSigma
    -- hence invariant under shift, so Koopman fixes it
    sorry
  · -- (⊇) fixedSubspace ⊆ Range of condexpL2
    intro hf
    -- If f is fixed by Koopman, then f is shift-invariant a.e.
    -- hence measurable w.r.t. shiftInvariantSigma
    -- so f = condexpL2 f
    use f
    sorry

end LeantestAfp.Probability.DeFinetti
