/-
Copyright (c) 2025 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Unique
import Mathlib.MeasureTheory.Function.AEEqOfIntegral
import Mathlib.Probability.ConditionalExpectation

/-!
# Helper lemmas for conditional expectation

This file contains helper lemmas for working with conditional expectations,
particularly for uniqueness arguments via set integrals and σ-algebra factorizations.

These lemmas support the proof of de Finetti's theorem via martingales, specifically
the three key lemmas about conditional independence and factorization.

## Main results

* `sigma_factor_le`: Pullback σ-algebra inequality for factorizations

## Implementation notes

These are minimal "workaround" lemmas that wrap or slightly extend mathlib's
conditional expectation API for the specific needs of the de Finetti proof.

-/

noncomputable section
open scoped MeasureTheory ENNReal
open MeasureTheory ProbabilityTheory Set

/-!
## σ-algebra factorization
-/

/-- **Pullback σ-algebra inequality for factorizations.**

If `η = g ∘ ζ` with `g` measurable, then the σ-algebra generated by `η`
is contained in the σ-algebra generated by `ζ`.

This is the fundamental fact about σ-algebra factorization: knowing `ζ` gives
you at least as much information as knowing `η = g(ζ)`.

**Mathematical statement:** σ(η) ≤ σ(ζ) when η = g ∘ ζ.
-/
lemma sigma_factor_le {Ω α β : Type*}
    [MeasurableSpace Ω] [MeasurableSpace α] [MeasurableSpace β]
    {η : Ω → α} {ζ : Ω → β} {g : β → α}
    (hη : η = g ∘ ζ) (hg : Measurable g) :
    MeasurableSpace.comap η inferInstance ≤ MeasurableSpace.comap ζ inferInstance := by
  -- Key idea: η = g ∘ ζ with g measurable implies σ(η) ≤ σ(ζ)
  -- Every η-measurable set has form η⁻¹(t) = (g∘ζ)⁻¹(t) = ζ⁻¹(g⁻¹(t))
  intro s hs
  -- hs : s ∈ σ(η) means s = η⁻¹(t) for some measurable t
  obtain ⟨t, ht, rfl⟩ := hs
  -- Rewrite using hη: η⁻¹(t) = ζ⁻¹(g⁻¹(t))
  rw [hη, Set.preimage_comp]
  -- Goal: ζ⁻¹(g⁻¹(t)) ∈ σ(ζ)
  exact ⟨g ⁻¹' t, hg ht, rfl⟩

/-!
## Convenience lemmas for set integrals
-/

namespace MeasureTheory

/-- Shorthand for the conditional expectation uniqueness lemma from mathlib.
Given that integrals over all m-measurable sets coincide, deduce the condexp is equal to g. -/
lemma condExp_eq_of_setIntegral_eq {α : Type*} {mα : MeasurableSpace α} {μ : Measure α}
    {m : MeasurableSpace α} (hm : m ≤ mα) [SigmaFinite (Measure.trim μ hm)]
    {f g : α → ℝ}
    (hg_meas : @Measurable α ℝ m _ g)
    (hf_int : Integrable f μ)
    (hg_int : Integrable g μ)
    (h : ∀ s, @MeasurableSet α m s → μ s < ∞ → ∫ x in s, f x ∂μ = ∫ x in s, g x ∂μ) :
    μ[f | m] =ᵐ[μ] g := by
  refine (ae_eq_condExp_of_forall_setIntegral_eq hm hf_int ?_ ?_ ?_).symm
  · intro s hs hμs
    exact hg_int.integrableOn
  · intro s hs hμs
    exact (h s hs hμs).symm
  · exact (Measurable.mono hg_meas hm le_rfl).aestronglyMeasurable

end MeasureTheory

end
