/-
Copyright (c) 2025 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.Constructions.Pi
import Mathlib.MeasureTheory.PiSystem
import Mathlib.Probability.Kernel.Basic

/-!
# Measurability of Product Measure Kernels

This file contains technical lemmas about measurability of product measure kernels.
These lemmas support the de Finetti theorem proof machinery but are general-purpose
results about measure theory on product spaces.

## Main results

* `measurable_prod_ennreal`: Products of measurable ENNReal functions are measurable
* `rectangles_isPiSystem`: Measurable rectangles form a π-system
* `rectangles_generate_pi_sigma`: The product σ-algebra equals the σ-algebra generated by rectangles
* `measurable_measure_pi`: Measurability of product measure kernels ω ↦ ∏ᵢ ν ω
* `aemeasurable_measure_pi`: AE-measurability version (implies measurable version)

## Implementation notes

These lemmas were extracted from `CommonEnding.lean` to break circular dependencies
between `ConditionallyIID.lean` and `CommonEnding.lean`.

The key technique is π-system induction: proving measurability on rectangles (a π-system)
and extending to all measurable sets via the π-λ theorem.

## References

* Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*
-/

noncomputable section
open scoped BigOperators MeasureTheory
open MeasureTheory ProbabilityTheory Set

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-!
## Preliminary lemmas
-/

/-- The product of finitely many measurable ENNReal-valued functions is measurable.

This is a wrapper around `Finset.measurable_prod` specialized to ENNReal.
-/
lemma measurable_prod_ennreal {ι : Type*} [Fintype ι] {Ω : Type*} [MeasurableSpace Ω]
    (f : ι → Ω → ENNReal) (hf : ∀ i, Measurable (f i)) :
    Measurable fun ω => ∏ i, f i ω := by
  apply Finset.measurable_prod
  intro i _
  exact hf i

/-- Rewrite `Set.univ.pi B` as a setOf comprehension.

This is a convenience lemma for working with measurable rectangles in product spaces.
The two forms are definitionally equal but different proof strategies prefer different forms:
- `Set.univ.pi B` is convenient for applying `Measure.pi_pi`
- `{x | ∀ i, x i ∈ B i}` is convenient for membership reasoning
-/
lemma univ_pi_eq_setOf_forall {ι : Type*} {α : Type*} (B : ι → Set α) :
    Set.univ.pi B = {x | ∀ i, x i ∈ B i} := by
  ext x; simp [Set.pi]

/-!
## π-system structure of rectangles
-/

/-- Measurable rectangles form a π-system for the product σ-algebra.

A rectangle in (Fin m → α) is a set of the form {x | ∀ i, x i ∈ B i} where each B i
is measurable. The collection of such rectangles is closed under finite intersections.
-/
lemma rectangles_isPiSystem {m : ℕ} {α : Type*} [MeasurableSpace α] :
    IsPiSystem {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} := by
  intro S₁ hS₁ S₂ hS₂ _hne
  -- S₁ and S₂ are rectangles
  obtain ⟨B₁, hB₁_meas, rfl⟩ := hS₁
  obtain ⟨B₂, hB₂_meas, rfl⟩ := hS₂
  -- Their intersection is also a rectangle
  use fun i => B₁ i ∩ B₂ i
  constructor
  · intro i
    exact (hB₁_meas i).inter (hB₂_meas i)
  · ext x
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
    constructor
    · intro ⟨h₁, h₂⟩ i
      exact ⟨h₁ i, h₂ i⟩
    · intro h
      exact ⟨fun i => (h i).1, fun i => (h i).2⟩

/-- The product σ-algebra on (Fin m → α) is generated by measurable rectangles.

This is a fundamental result in product measure theory: the σ-algebra on a finite
product equals the σ-algebra generated by measurable rectangles.

Proof strategy:
- The product σ-algebra is the smallest σ-algebra making all projections measurable
- A set is in this σ-algebra iff it's in the σ-algebra generated by cylinder sets
- Cylinder sets are finite intersections of preimages of projections
- These are exactly the rectangles

In mathlib, this follows from `generateFrom_pi` which establishes the equivalence
between the product σ-algebra and the σ-algebra generated by rectangles.
-/
lemma rectangles_generate_pi_sigma {m : ℕ} {α : Type*} [MeasurableSpace α] :
    (inferInstance : MeasurableSpace (Fin m → α)) =
    MeasurableSpace.generateFrom {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} := by
  -- The key insight: mathlib's generateFrom_pi shows that for finite index sets,
  -- the product σ-algebra equals the σ-algebra generated by measurable rectangles

  -- First establish the set equality: our rectangles match mathlib's rectangle format
  have set_eq : {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} =
      Set.pi univ '' Set.pi univ fun i : Fin m => {s : Set α | MeasurableSet s} := by
    ext S
    constructor
    · intro ⟨B, hB_meas, hS⟩
      use fun i => B i
      simp only [Set.mem_pi]
      constructor
      · intro i _; exact hB_meas i
      · have : univ.pi (fun i => B i) = {x | ∀ i, x i ∈ B i} := by
          ext x; simp [Set.pi]
        rw [this]; exact hS.symm
    · intro ⟨B, hB_mem, hS⟩
      simp only [Set.mem_pi, Set.mem_univ, Set.mem_setOf_eq] at hB_mem hS
      use B
      constructor
      · exact fun i => hB_mem i (Set.mem_univ i)
      · have : univ.pi (fun i => B i) = {x | ∀ i, x i ∈ B i} := by
          ext x; simp [Set.pi]
        rw [← this]; exact hS.symm

  rw [set_eq]
  exact generateFrom_pi.symm

/-!
## Measurability of product measure kernels
-/

/-- The product measure kernel ω ↦ Measure.pi (fun _ => ν ω) is measurable.

Given a measurable family of probability measures ν : Ω → Measure α, the product
kernel ω ↦ ∏ᵢ ν ω (where i ranges over Fin m) is measurable as a measure-valued map.

**Proof strategy**: Use π-system induction on rectangles:
1. Rectangles generate the product σ-algebra (`rectangles_generate_pi_sigma`)
2. Rectangles form a π-system (`rectangles_isPiSystem`)
3. On rectangles, the product measure of {x | ∀ i, x i ∈ B i} equals ∏ᵢ ν ω (B i),
   which is measurable in ω by `measurable_prod_ennreal`
4. By the π-λ theorem (`Measurable.measure_of_isPiSystem_of_isProbabilityMeasure`),
   measurability on the generating π-system extends to all measurable sets

This is a key lemma for proving the ConditionallyIID property in de Finetti's theorem.

**Mathematical content**: This shows that finite products of probability kernels
yield measurable kernels, which is essential for disintegration theory and
conditional independence.
-/
lemma measurable_measure_pi {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    {m : ℕ}
    (ν : Ω → Measure α) (hν_prob : ∀ ω, IsProbabilityMeasure (ν ω))
    (hν_meas : ∀ s, MeasurableSet s → Measurable (fun ω => ν ω s)) :
    Measurable fun ω => Measure.pi fun _ : Fin m => ν ω := by
  classical
  -- Abbreviation for the product kernel
  let κ : Ω → Measure (Fin m → α) := fun ω => Measure.pi fun _ : Fin m => ν ω
  -- Rectangular generator and π-system for the product σ-algebra
  let 𝒞 : Set (Set (Fin m → α)) :=
    {S | ∃ (B : Fin m → Set α), (∀ i, MeasurableSet (B i)) ∧
        S = {x | ∀ i, x i ∈ B i}}

  have h_gen : (inferInstance : MeasurableSpace (Fin m → α))
      = MeasurableSpace.generateFrom 𝒞 :=
    rectangles_generate_pi_sigma (m := m) (α := α)
  have h_pi : IsPiSystem 𝒞 := rectangles_isPiSystem (m := m) (α := α)

  -- Values on rectangles are measurable
  have h_basic : ∀ t ∈ 𝒞, Measurable fun ω => κ ω t := by
    intro t ht
    rcases ht with ⟨B, hB, rfl⟩
    have rect : (fun ω => κ ω {x : Fin m → α | ∀ i, x i ∈ B i})
        = fun ω => ∏ i : Fin m, ν ω (B i) := by
      funext ω
      have : {x : Fin m → α | ∀ i, x i ∈ B i}
          = Set.univ.pi fun i => B i := by
        ext x; simp [Set.pi]
      simp [κ, this, Measure.pi_pi]
    have hfac : ∀ i, Measurable fun ω => ν ω (B i) := by
      intro i; exact hν_meas (B i) (hB i)
    have hmeas : Measurable fun ω => ∏ i : Fin m, ν ω (B i) :=
      measurable_prod_ennreal (fun i ω => ν ω (B i)) hfac
    simpa [κ, rect]

  -- Each product measure is a probability measure
  have hκ_prob : ∀ ω, IsProbabilityMeasure (κ ω) := by
    intro ω
    classical
    haveI : ∀ _ : Fin m, IsProbabilityMeasure (ν ω) := fun _ => hν_prob ω
    simp only [κ]
    infer_instance

  -- Apply π-λ theorem to extend measurability from rectangles to all measurable sets
  exact Measurable.measure_of_isPiSystem_of_isProbabilityMeasure
    (μ := κ) (S := 𝒞) h_gen h_pi h_basic

/-- AE-measurable version of `measurable_measure_pi`.

This is the version originally proved in `CommonEnding.lean`. The measurable version
`measurable_measure_pi` is stronger and generally more useful, but this AE version
is kept for compatibility.

Note: The hypothesis only requires measurability for **measurable** sets, matching
what `Kernel.measurable_coe` provides. This is the standard requirement in measure theory.
-/
lemma aemeasurable_measure_pi {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    {μ : Measure Ω} {m : ℕ}
    (ν : Ω → Measure α) (hν_prob : ∀ ω, IsProbabilityMeasure (ν ω))
    (hν_meas : ∀ s, MeasurableSet s → Measurable (fun ω => ν ω s)) :
    AEMeasurable (fun ω => Measure.pi fun _ : Fin m => ν ω) μ := by
  -- The measurable version immediately implies AE-measurability
  have h_meas : Measurable fun ω => Measure.pi fun _ : Fin m => ν ω := by
    apply measurable_measure_pi ν hν_prob
    exact hν_meas
  exact h_meas.aemeasurable
