/-
Copyright (c) 2025 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.Constructions.Pi
import Mathlib.MeasureTheory.PiSystem
import Mathlib.Probability.Kernel.Basic

/-!
# Measurability of Product Measure Kernels

This file contains technical lemmas about measurability of product measure kernels.
These lemmas support the de Finetti theorem proof machinery but are general-purpose
results about measure theory on product spaces.

## Main results

* `measurable_prod_ennreal`: Products of measurable ENNReal functions are measurable
* `rectangles_isPiSystem`: Measurable rectangles form a π-system
* `rectangles_generate_pi_sigma`: The product σ-algebra equals the σ-algebra generated by rectangles
* `measurable_measure_pi`: Measurability of product measure kernels ω ↦ ∏ᵢ ν ω
* `aemeasurable_measure_pi`: AE-measurability version (implies measurable version)

## Implementation notes

These lemmas were extracted from `CommonEnding.lean` to break circular dependencies
between `ConditionallyIID.lean` and `CommonEnding.lean`.

The key technique is π-system induction: proving measurability on rectangles (a π-system)
and extending to all measurable sets via the π-λ theorem.

## References

* Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*
-/

noncomputable section
open scoped BigOperators MeasureTheory
open MeasureTheory ProbabilityTheory Set

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-!
## Preliminary lemmas
-/

/-- The product of finitely many measurable ENNReal-valued functions is measurable.

This is a wrapper around `Finset.measurable_prod` specialized to ENNReal.
-/
@[measurability, fun_prop]
lemma measurable_prod_ennreal {ι : Type*} [Fintype ι] {Ω : Type*} [MeasurableSpace Ω]
    (f : ι → Ω → ENNReal) (hf : ∀ i, Measurable (f i)) :
    Measurable fun ω => ∏ i, f i ω :=
  Finset.measurable_prod _ fun i _ => hf i

/-- Rewrite `Set.univ.pi B` as a setOf comprehension.

This is a convenience lemma for working with measurable rectangles in product spaces.
The two forms are definitionally equal but different proof strategies prefer different forms:
- `Set.univ.pi B` is convenient for applying `Measure.pi_pi`
- `{x | ∀ i, x i ∈ B i}` is convenient for membership reasoning
-/
lemma univ_pi_eq_setOf_forall {ι : Type*} {α : Type*} (B : ι → Set α) :
    Set.univ.pi B = {x | ∀ i, x i ∈ B i} := by
  ext x; simp [Set.pi]

/-!
## π-system structure of rectangles
-/

/-- Measurable rectangles form a π-system for the product σ-algebra.

A rectangle in (Fin m → α) is a set of the form {x | ∀ i, x i ∈ B i} where each B i
is measurable. The collection of such rectangles is closed under finite intersections.
-/
lemma rectangles_isPiSystem {m : ℕ} {α : Type*} [MeasurableSpace α] :
    IsPiSystem {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} := by
  intro S₁ hS₁ S₂ hS₂ _hne
  -- S₁ and S₂ are rectangles
  obtain ⟨B₁, hB₁_meas, rfl⟩ := hS₁
  obtain ⟨B₂, hB₂_meas, rfl⟩ := hS₂
  -- Their intersection is also a rectangle
  use fun i => B₁ i ∩ B₂ i
  constructor
  · intro i
    exact (hB₁_meas i).inter (hB₂_meas i)
  · ext x
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq]
    constructor
    · intro ⟨h₁, h₂⟩ i
      exact ⟨h₁ i, h₂ i⟩
    · intro h
      exact ⟨fun i => (h i).1, fun i => (h i).2⟩

/-- The product σ-algebra on (Fin m → α) is generated by measurable rectangles.

This is a fundamental result in product measure theory: the σ-algebra on a finite
product equals the σ-algebra generated by measurable rectangles.

Proof strategy:
- The product σ-algebra is the smallest σ-algebra making all projections measurable
- A set is in this σ-algebra iff it's in the σ-algebra generated by cylinder sets
- Cylinder sets are finite intersections of preimages of projections
- These are exactly the rectangles

In mathlib, this follows from `generateFrom_pi` which establishes the equivalence
between the product σ-algebra and the σ-algebra generated by rectangles.
-/
lemma rectangles_generate_pi_sigma {m : ℕ} {α : Type*} [MeasurableSpace α] :
    (inferInstance : MeasurableSpace (Fin m → α)) =
    MeasurableSpace.generateFrom {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} := by
  -- The key insight: mathlib's generateFrom_pi shows that for finite index sets,
  -- the product σ-algebra equals the σ-algebra generated by measurable rectangles

  -- First establish the set equality: our rectangles match mathlib's rectangle format
  have set_eq : {S : Set (Fin m → α) | ∃ (B : Fin m → Set α),
      (∀ i, MeasurableSet (B i)) ∧ S = {x | ∀ i, x i ∈ B i}} =
      Set.pi univ '' Set.pi univ fun i : Fin m => {s : Set α | MeasurableSet s} := by
    ext S
    constructor
    · intro ⟨B, hB_meas, hS⟩
      use fun i => B i
      simp only [Set.mem_pi]
      constructor
      · exact fun i _ => hB_meas i
      · rw [univ_pi_eq_setOf_forall]; exact hS.symm
    · intro ⟨B, hB_mem, hS⟩
      simp only [Set.mem_pi, Set.mem_univ, Set.mem_setOf_eq] at hB_mem hS
      use B
      constructor
      · exact fun i => hB_mem i (Set.mem_univ i)
      · rw [← univ_pi_eq_setOf_forall]; exact hS.symm

  rw [set_eq]
  exact generateFrom_pi.symm

/-!
## Measurability of product measure kernels
-/

/-- The product measure kernel ω ↦ Measure.pi (fun _ => ν ω) is measurable.

Given a measurable family of probability measures ν : Ω → Measure α, the product
kernel ω ↦ ∏ᵢ ν ω (where i ranges over Fin m) is measurable as a measure-valued map.

**Proof strategy**: Use π-system induction on rectangles:
1. Rectangles generate the product σ-algebra (`rectangles_generate_pi_sigma`)
2. Rectangles form a π-system (`rectangles_isPiSystem`)
3. On rectangles, the product measure of {x | ∀ i, x i ∈ B i} equals ∏ᵢ ν ω (B i),
   which is measurable in ω by `measurable_prod_ennreal`
4. By the π-λ theorem (`Measurable.measure_of_isPiSystem_of_isProbabilityMeasure`),
   measurability on the generating π-system extends to all measurable sets

This is a key lemma for proving the ConditionallyIID property in de Finetti's theorem.

**Mathematical content**: This shows that finite products of probability kernels
yield measurable kernels, which is essential for disintegration theory and
conditional independence.
-/
@[measurability, fun_prop]
lemma measurable_measure_pi {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    {m : ℕ}
    (ν : Ω → Measure α) (hν_prob : ∀ ω, IsProbabilityMeasure (ν ω))
    (hν_meas : ∀ s, MeasurableSet s → Measurable (fun ω => ν ω s)) :
    Measurable fun ω => Measure.pi fun _ : Fin m => ν ω := by
  classical
  -- Abbreviation for the product kernel
  let κ : Ω → Measure (Fin m → α) := fun ω => Measure.pi fun _ : Fin m => ν ω
  -- Rectangular generator and π-system for the product σ-algebra
  let 𝒞 : Set (Set (Fin m → α)) :=
    {S | ∃ (B : Fin m → Set α), (∀ i, MeasurableSet (B i)) ∧
        S = {x | ∀ i, x i ∈ B i}}

  have h_gen : (inferInstance : MeasurableSpace (Fin m → α))
      = MeasurableSpace.generateFrom 𝒞 :=
    rectangles_generate_pi_sigma (m := m) (α := α)
  have h_pi : IsPiSystem 𝒞 := rectangles_isPiSystem (m := m) (α := α)

  -- Values on rectangles are measurable
  have h_basic : ∀ t ∈ 𝒞, Measurable fun ω => κ ω t := by
    intro t ht
    rcases ht with ⟨B, hB, rfl⟩
    have rect : (fun ω => κ ω {x : Fin m → α | ∀ i, x i ∈ B i})
        = fun ω => ∏ i : Fin m, ν ω (B i) := by
      funext ω
      have : {x : Fin m → α | ∀ i, x i ∈ B i}
          = Set.univ.pi fun i => B i := by
        ext x; simp [Set.pi]
      simp [κ, this, Measure.pi_pi]
    have hfac : ∀ i, Measurable fun ω => ν ω (B i) := fun i => hν_meas (B i) (hB i)
    have hmeas : Measurable fun ω => ∏ i : Fin m, ν ω (B i) :=
      measurable_prod_ennreal (fun i ω => ν ω (B i)) hfac
    simpa [κ, rect]

  -- Each product measure is a probability measure
  have hκ_prob : ∀ ω, IsProbabilityMeasure (κ ω) := by
    intro ω
    classical
    haveI : ∀ _ : Fin m, IsProbabilityMeasure (ν ω) := fun _ => hν_prob ω
    simp only [κ]
    infer_instance

  -- Apply π-λ theorem to extend measurability from rectangles to all measurable sets
  exact Measurable.measure_of_isPiSystem_of_isProbabilityMeasure
    (μ := κ) (S := 𝒞) h_gen h_pi h_basic

/-- AE-measurable version of `measurable_measure_pi`.

This is the version originally proved in `CommonEnding.lean`. The measurable version
`measurable_measure_pi` is stronger and generally more useful, but this AE version
is kept for compatibility.

Note: The hypothesis only requires measurability for **measurable** sets, matching
what `Kernel.measurable_coe` provides. This is the standard requirement in measure theory.
-/
lemma aemeasurable_measure_pi {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    {μ : Measure Ω} {m : ℕ}
    (ν : Ω → Measure α) (hν_prob : ∀ ω, IsProbabilityMeasure (ν ω))
    (hν_meas : ∀ s, MeasurableSet s → Measurable (fun ω => ν ω s)) :
    AEMeasurable (fun ω => Measure.pi fun _ : Fin m => ν ω) μ := by
  -- The measurable version immediately implies AE-measurability
  have h_meas : Measurable fun ω => Measure.pi fun _ : Fin m => ν ω := by
    apply measurable_measure_pi ν hν_prob
    exact hν_meas
  exact h_meas.aemeasurable

/-!
## Triple product rectangles

These lemmas support σ-algebra arguments on triple products of the form
`(Fin r → α) × α × (Fin k → α)`, which arise in the contractable triple pushforward lemma.
-/

/-- Definition of triple rectangles: sets of the form (pi A) × B × (pi C). -/
def TripleRectangles (r k : ℕ) (α : Type*) [MeasurableSpace α] :
    Set (Set ((Fin r → α) × α × (Fin k → α))) :=
  {S | ∃ (A : Fin r → Set α) (_ : ∀ i, MeasurableSet (A i))
        (B : Set α) (_ : MeasurableSet B)
        (C : Fin k → Set α) (_ : ∀ j, MeasurableSet (C j)),
      S = (Set.univ.pi A) ×ˢ B ×ˢ (Set.univ.pi C)}

/-- Triple rectangles form a π-system.

The intersection of two triple rectangles is another triple rectangle, obtained
by intersecting each component. -/
lemma tripleRectangles_isPiSystem {r k : ℕ} {α : Type*} [MeasurableSpace α] :
    IsPiSystem (TripleRectangles r k α) := by
  intro S₁ hS₁ S₂ hS₂ _
  rcases hS₁ with ⟨A₁, hA₁, B₁, hB₁, C₁, hC₁, rfl⟩
  rcases hS₂ with ⟨A₂, hA₂, B₂, hB₂, C₂, hC₂, rfl⟩
  refine ⟨fun i => A₁ i ∩ A₂ i, ?_, B₁ ∩ B₂, hB₁.inter hB₂,
          fun j => C₁ j ∩ C₂ j, ?_, ?_⟩
  · intro i; exact (hA₁ i).inter (hA₂ i)
  · intro j; exact (hC₁ j).inter (hC₂ j)
  · ext ⟨z, y, c⟩
    simp only [Set.mem_inter_iff, Set.mem_prod, Set.mem_univ_pi]
    constructor
    · intro ⟨⟨hz1, hy1, hc1⟩, hz2, hy2, hc2⟩
      exact ⟨fun i => ⟨hz1 i, hz2 i⟩, ⟨hy1, hy2⟩, fun j => ⟨hc1 j, hc2 j⟩⟩
    · intro ⟨hz, hy, hc⟩
      exact ⟨⟨fun i => (hz i).1, hy.1, fun j => (hc j).1⟩,
             fun i => (hz i).2, hy.2, fun j => (hc j).2⟩

/-- The product σ-algebra on (Fin r → α) × α × (Fin k → α) is generated by triple rectangles.

This is a key structural lemma for π-λ induction on triple products. It shows that
to prove equality of measures on the triple product, it suffices to prove equality
on triple rectangles (provided one shows they form a π-system). -/
lemma tripleRectangles_generate {r k : ℕ} {α : Type*} [MeasurableSpace α] :
    (inferInstance : MeasurableSpace ((Fin r → α) × α × (Fin k → α)))
      = MeasurableSpace.generateFrom (TripleRectangles r k α) := by
  apply le_antisymm
  · -- (⊆) Product σ-algebra ≤ generateFrom TripleRectangles
    -- Show each projection is measurable w.r.t. generateFrom TripleRectangles

    -- First projection: (Fin r → α)
    have h_fst : ∀ (A : Fin r → Set α), (∀ i, MeasurableSet (A i)) →
        MeasurableSet[MeasurableSpace.generateFrom (TripleRectangles r k α)]
          (Prod.fst ⁻¹' (Set.univ.pi A)) := fun A hA => by
      refine MeasurableSpace.measurableSet_generateFrom ⟨A, hA, Set.univ, .univ, fun _ => Set.univ,
        fun _ => .univ, ?_⟩
      ext ⟨z, y, c⟩; simp

    -- Second projection (middle component): α
    have h_fst_snd : ∀ (B : Set α), MeasurableSet B →
        MeasurableSet[MeasurableSpace.generateFrom (TripleRectangles r k α)]
          ((Prod.fst ∘ Prod.snd) ⁻¹' B) := fun B hB => by
      refine MeasurableSpace.measurableSet_generateFrom ⟨fun _ => Set.univ, fun _ => .univ,
        B, hB, fun _ => Set.univ, fun _ => .univ, ?_⟩
      ext ⟨z, y, c⟩; simp

    -- Third projection: (Fin k → α)
    have h_snd_snd : ∀ (C : Fin k → Set α), (∀ j, MeasurableSet (C j)) →
        MeasurableSet[MeasurableSpace.generateFrom (TripleRectangles r k α)]
          ((Prod.snd ∘ Prod.snd) ⁻¹' (Set.univ.pi C)) := fun C hC => by
      refine MeasurableSpace.measurableSet_generateFrom ⟨fun _ => Set.univ, fun _ => .univ,
        Set.univ, .univ, C, hC, ?_⟩
      ext ⟨z, y, c⟩; simp

    -- Comap of first projection ≤ generateFrom
    have h_fst_comap : MeasurableSpace.comap Prod.fst inferInstance
        ≤ MeasurableSpace.generateFrom (TripleRectangles r k α) := by
      rw [← measurable_iff_comap_le]
      rw [MeasurableSpace.pi_eq_generateFrom_projections (ι := Fin r) (α := fun _ => α)]
      apply @measurable_generateFrom _ _ (MeasurableSpace.generateFrom (TripleRectangles r k α)) _ _
      intro s hs
      obtain ⟨i, A, hA, rfl⟩ := hs
      let D : Fin r → Set α := fun j => if j = i then A else Set.univ
      have hD : ∀ j, MeasurableSet (D j) := by
        intro j; simp only [D]; split_ifs; exact hA; exact MeasurableSet.univ
      have : (fun f : Fin r → α => f i) ⁻¹' A = Set.univ.pi D := by
        ext f; simp only [D, Set.mem_preimage, Set.mem_univ_pi]
        constructor
        · intro hf j; by_cases h : j = i <;> simp [h, hf]
        · intro hf; simpa using hf i
      rw [this]
      exact h_fst D hD

    -- Comap of middle projection ≤ generateFrom
    have h_fst_snd_comap : MeasurableSpace.comap (Prod.fst ∘ Prod.snd) inferInstance
        ≤ MeasurableSpace.generateFrom (TripleRectangles r k α) := by
      intro s hs
      obtain ⟨B, hB, rfl⟩ := hs
      exact h_fst_snd B hB

    -- Comap of third projection ≤ generateFrom
    have h_snd_snd_comap : MeasurableSpace.comap (Prod.snd ∘ Prod.snd) inferInstance
        ≤ MeasurableSpace.generateFrom (TripleRectangles r k α) := by
      rw [← measurable_iff_comap_le]
      rw [MeasurableSpace.pi_eq_generateFrom_projections (ι := Fin k) (α := fun _ => α)]
      apply @measurable_generateFrom _ _ (MeasurableSpace.generateFrom (TripleRectangles r k α)) _ _
      intro s hs
      obtain ⟨j, C, hC, rfl⟩ := hs
      let D : Fin k → Set α := fun i => if i = j then C else Set.univ
      have hD : ∀ i, MeasurableSet (D i) := by
        intro i; simp only [D]; split_ifs; exact hC; exact MeasurableSet.univ
      have : (fun f : Fin k → α => f j) ⁻¹' C = Set.univ.pi D := by
        ext f; simp only [D, Set.mem_preimage, Set.mem_univ_pi]
        constructor
        · intro hf i; by_cases h : i = j <;> simp [h, hf]
        · intro hf; simpa using hf j
      rw [this]
      exact h_snd_snd D hD

    -- The product σ-algebra is comap fst ⊔ comap snd
    have : (inferInstance : MeasurableSpace ((Fin r → α) × α × (Fin k → α))) =
        MeasurableSpace.comap Prod.fst inferInstance ⊔
        MeasurableSpace.comap Prod.snd inferInstance := rfl
    rw [this]

    -- Comap snd decomposes into comap (fst ∘ snd) ⊔ comap (snd ∘ snd)
    have h_snd_le : MeasurableSpace.comap
        (Prod.snd : (Fin r → α) × α × (Fin k → α) → α × (Fin k → α)) inferInstance
        ≤ MeasurableSpace.generateFrom (TripleRectangles r k α) := by
      calc MeasurableSpace.comap
            (Prod.snd : (Fin r → α) × α × (Fin k → α) → α × (Fin k → α)) inferInstance
          = MeasurableSpace.comap Prod.snd
              (MeasurableSpace.comap Prod.fst inferInstance ⊔
               MeasurableSpace.comap Prod.snd inferInstance) := rfl
        _ = MeasurableSpace.comap Prod.snd (MeasurableSpace.comap Prod.fst inferInstance)
            ⊔ MeasurableSpace.comap Prod.snd (MeasurableSpace.comap Prod.snd inferInstance) := by
              rw [MeasurableSpace.comap_sup]
        _ = MeasurableSpace.comap (Prod.fst ∘ Prod.snd) inferInstance
            ⊔ MeasurableSpace.comap (Prod.snd ∘ Prod.snd) inferInstance := by
              rw [MeasurableSpace.comap_comp, MeasurableSpace.comap_comp]
        _ ≤ MeasurableSpace.generateFrom (TripleRectangles r k α) :=
              sup_le h_fst_snd_comap h_snd_snd_comap
    exact sup_le h_fst_comap h_snd_le

  · -- (⊇) generateFrom TripleRectangles ≤ Product σ-algebra
    apply MeasurableSpace.generateFrom_le
    intro t ht
    obtain ⟨A, hA, B, hB, C, hC, rfl⟩ := ht
    exact (MeasurableSet.univ_pi hA).prod (hB.prod (MeasurableSet.univ_pi hC))
