/-
Copyright (c) 2025 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.Probability.IdentDistrib
import Mathlib.Probability.Kernel.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Exchangeability.Contractability
import Exchangeability.ConditionallyIID

/-!
# De Finetti's Theorem - Common Infrastructure

This module contains the **common scaffolding** for de Finetti's theorem,
including the tail σ-algebra definition and the main theorem statements.

## Main theorem

* `deFinetti`: An infinite exchangeable sequence on a Borel space is conditionally
  i.i.d. given the tail σ-algebra.

## Three proof approaches (Kallenberg 2005)

This formalization keeps track of all three proofs of Theorem 1.1 highlighted by
Kallenberg. The **complete proofs** are in separate files to manage dependencies:

1. **First proof** (`ViaKoopman.lean`): Uses the Mean Ergodic Theorem via the
   Koopman operator on L²(μ). Heavy dependencies (ergodic theory).

2. **Second proof** (`ViaL2.lean`): Uses an elementary L² contractability bound
   (Lemma 1.2). **Lightest dependencies** - this is the default.

3. **Third proof** (`ViaMartingale.lean`): Follows Aldous' martingale argument
   with reverse martingale convergence. Medium dependencies.

**To use the theorem**: `import Exchangeability.DeFinetti.Theorem` (gets the default proof).

**To see a specific proof**: `import Exchangeability.DeFinetti.ViaL2` (or `ViaKoopman`, `ViaMartingale`).

## References

* Olav Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*,
  Springer, Chapter 1 (Theorem 1.1, pages 26-27).
* Bruno De Finetti (1937), *La prévision : ses lois logiques, ses sources
  subjectives*, Annales de l'institut Henri Poincaré.
* David Aldous (1983), *Exchangeability and related topics*, École d'Été de
  Probabilités de Saint-Flour XIII.

-/

noncomputable section
open scoped BigOperators MeasureTheory Topology Classical

namespace Exchangeability
namespace Probability

open MeasureTheory Filter

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-- The tail `σ`-algebra generated by the tails of the process `X`.  It is the
intersection of the `σ`-algebras generated by the coordinates from `n`
onwards. -/
def tailSigmaAlgebra (X : ℕ → Ω → α) : MeasurableSpace Ω :=
  ⨅ n : ℕ, MeasurableSpace.comap (fun ω => fun k : ℕ => X (n + k) ω) inferInstance

/-!
## Conditionally i.i.d. sequences

### Definition from `Exchangeability.ConditionallyIID`

A sequence `X : ℕ → Ω → α` is **conditionally i.i.d.** with respect to measure `μ` if:
```lean
∃ ν : Ω → Measure α,
  (∀ ω, IsProbabilityMeasure (ν ω)) ∧
  ∀ (m : ℕ) (k : Fin m → ℕ),
    Measure.map (fun ω => fun i : Fin m => X (k i) ω) μ
      = μ.bind (fun ω => Measure.pi fun _ : Fin m => ν ω)
```

This expresses that:
1. There exists a probability kernel `ν : Ω → Measure α`
2. For every finite selection of indices `k : Fin m → ℕ`
3. The joint distribution of `(X (k 0), ..., X (k (m-1)))` equals
4. The mixture `μ.bind (ν ↦ ν^⊗m)` of i.i.d. product measures

### Key Properties

- **From mathlib**: Uses `Measure.pi` (finite products) and `Measure.bind` (Giry monad)
- **Proved in ConditionallyIID.lean**: `exchangeable_of_conditionallyIID`
- **For de Finetti**: The kernel is tail-measurable (constructed via ergodic theory)

### DirectingMeasure structure

An alternative bundled formulation that explicitly carries the kernel and its properties.
-/

/-- A directing measure for a process `X` is a tail-measurable Markov kernel.

This bundles the kernel with its key properties needed for de Finetti's theorem.

**Note**: This is an alternative formulation that explicitly carries the kernel.
The main `ConditionallyIID` definition is existential and doesn't expose the kernel.
-/
structure DirectingMeasure (μ : Measure Ω) [IsProbabilityMeasure μ] (X : ℕ → Ω → α) where
  /-- The probability kernel -/
  kernel : ProbabilityTheory.Kernel Ω α
  /-- The kernel is a Markov kernel (maps to probability measures) -/
  is_markov : ProbabilityTheory.IsMarkovKernel kernel
  -- Tail measurability would be expressed as:
  -- is_tail_measurable : @AEStronglyMeasurable' _ _ (tailSigmaAlgebra X) _ _ (fun ω ↦ kernel ω) μ
  -- TODO: Add this once we have proper tail σ-algebra infrastructure

/-- The empirical measure of the first `n` terms of the process `X`.

For `n = 0`, we define it as the Dirac measure on an arbitrary default value.
For `n > 0`, this is the uniform measure on `{X 0 ω, X 1 ω, ..., X (n-1) ω}`.
-/
def empiricalMeasure [Inhabited α] (X : ℕ → Ω → α) (n : ℕ) (ω : Ω) :
    ProbabilityMeasure α :=
  if h : n = 0 then
    ⟨Measure.dirac default, Measure.dirac.isProbabilityMeasure⟩
  else
    sorry
    -- TODO: Implement using uniform measure on Finset (Fin n)
    -- The uniform measure on a finite set can be constructed as:
    -- (1/n) • Σᵢ Measure.dirac (X i ω) where i ∈ Fin n
    -- Need to show this is a probability measure (total mass = 1)

/-!
## Main theorem statements

### Kallenberg Theorem 1.1 Structure

The theorem establishes a three-way equivalence (for Borel spaces):
- **(i)** ξ is **contractable**
- **(ii)** ξ is **exchangeable**
- **(iii)** ξ is **conditionally i.i.d.**

**Key insight from Kallenberg**: All three proofs start with contractability (i) and
directly establish conditionally i.i.d. (iii), with exchangeability (ii) coming along
automatically.

**Proof structure**:
- **(i) → (iii)**: The three approaches (Koopman, L², Martingale) all prove this directly
  - First proof (page 26): "If ξ is contractable..." uses mean ergodic theorem
  - Second proof (page 27): "If ξ is contractable..." uses L² bounds
  - Third proof (page 27): "If ξ is contractable, then..." uses martingale convergence
  - All three share the common ending in `Exchangeability.DeFinetti.CommonEnding`
- **(iii) → (ii)**: `exchangeable_of_conditionallyIID` ✓ **PROVED** in `ConditionallyIID.lean`
- **(ii) → (i)**: `contractable_of_exchangeable` ✓ **PROVED** in `Contractability.lean`

**Main theorems are proved in `Exchangeability.DeFinetti.Theorem`** (default L² proof).
Import that file to use the completed theorems.
-/

end Probability
end Exchangeability
