/-
Copyright (c) 2025 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.Probability.IdentDistrib
import Mathlib.Probability.Kernel.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Exchangeability.Contractability
import Exchangeability.ConditionallyIID

/-!
# De Finetti's Theorem - Common Infrastructure

This module contains the **common scaffolding** for de Finetti's theorem,
including the tail σ-algebra definition and the main theorem statements.

## Main theorem

* `deFinetti`: An infinite exchangeable sequence on a Borel space is conditionally
  i.i.d. given the tail σ-algebra.

## Three proof approaches (Kallenberg 2005)

All three proofs of Theorem 1.1 from Kallenberg are formalized. They differ in
machinery and target type:

1. **Martingale proof** (`ViaMartingale.lean`, re-exported by `DeFinetti.Theorem`
   as the default): Aldous' reverse martingale argument with tail σ-algebra
   factorization. The directing kernel is built via mathlib's `condExpKernel`.
   Handles general standard Borel target spaces.

2. **L² proof** (`ViaL2.lean`): Uses the elementary L² contractability bound
   (Kallenberg Lemma 1.2). Lightest dependencies among the three. Currently
   stated for real-valued sequences via the Stieltjes-based directing-measure
   construction.

3. **Koopman proof** (`ViaKoopman.lean`): Uses the Mean Ergodic Theorem via the
   Koopman operator on L²(μ). Heavier ergodic-theory dependencies. Currently
   stated for real-valued sequences.

**To use the theorem**: `import Exchangeability.DeFinetti.Theorem` (gets the
martingale proof).

**To see a specific proof**: `import Exchangeability.DeFinetti.ViaL2`,
`ViaKoopman`, or `ViaMartingale`.

## References

* Olav Kallenberg (2005), *Probabilistic Symmetries and Invariance Principles*,
  Springer, Chapter 1 (Theorem 1.1, pages 26-27).
* Bruno De Finetti (1937), *La prévision : ses lois logiques, ses sources
  subjectives*, Annales de l'institut Henri Poincaré.
* David Aldous (1983), *Exchangeability and related topics*, École d'Été de
  Probabilités de Saint-Flour XIII.

-/

noncomputable section
open scoped BigOperators MeasureTheory Topology Classical ENNReal

namespace Exchangeability
namespace Probability

open MeasureTheory Filter

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-- The tail `σ`-algebra generated by the tails of the process `X`.  It is the
intersection of the `σ`-algebras generated by the coordinates from `n`
onwards. -/
/-!
## Conditionally i.i.d. sequences

### Definition from `Exchangeability.ConditionallyIID`

A sequence `X : ℕ → Ω → α` is **conditionally i.i.d.** with respect to measure `μ` if:
```lean
∃ ν : Ω → Measure α,
  (∀ ω, IsProbabilityMeasure (ν ω)) ∧
  ∀ (m : ℕ) (k : Fin m → ℕ),
    Measure.map (fun ω => fun i : Fin m => X (k i) ω) μ
      = μ.bind (fun ω => Measure.pi fun _ : Fin m => ν ω)
```

This expresses that:
1. There exists a probability kernel `ν : Ω → Measure α`
2. For every finite selection of indices `k : Fin m → ℕ`
3. The joint distribution of `(X (k 0), ..., X (k (m-1)))` equals
4. The mixture `μ.bind (ν ↦ ν^⊗m)` of i.i.d. product measures

### Key Properties

- **From mathlib**: Uses `Measure.pi` (finite products) and `Measure.bind` (Giry monad)
- **Proved in ConditionallyIID.lean**: `exchangeable_of_conditionallyIID`
- **For de Finetti**: The kernel is tail-measurable (constructed via ergodic theory)

The theorem-facing abstraction is the existential `ConditionallyIID` above. Each
route builds the directing object through its own route-specific construction
(`ViaMartingale.directingMeasure_*`, `ViaL2.directing_measure_satisfies_requirements`,
`ViaKoopman.conditionallyIID_bind_of_contractable`); there is intentionally no
shared bundled wrapper.
-/

/-!
## Main theorem statements

### Kallenberg Theorem 1.1 Structure

The theorem establishes a three-way equivalence (for Borel spaces):
- **(i)** ξ is **contractable**
- **(ii)** ξ is **exchangeable**
- **(iii)** ξ is **conditionally i.i.d.**

**Key insight from Kallenberg**: All three proofs start with contractability (i) and
directly establish conditionally i.i.d. (iii), with exchangeability (ii) coming along
automatically.

**Proof structure**:
- **(i) → (iii)**: The three approaches (Koopman, L², Martingale) all prove this directly
  - First proof (page 26): "If ξ is contractable..." uses mean ergodic theorem
  - Second proof (page 27): "If ξ is contractable..." uses L² bounds
  - Third proof (page 27): "If ξ is contractable, then..." uses martingale convergence
  - All three share the common ending in `Exchangeability.DeFinetti.CommonEnding`
- **(iii) → (ii)**: `exchangeable_of_conditionallyIID` ✓ **PROVED** in `ConditionallyIID.lean`
- **(ii) → (i)**: `contractable_of_exchangeable` ✓ **PROVED** in `Contractability.lean`

**Main theorems are proved in `Exchangeability.DeFinetti.Theorem`** (which re-exports
the martingale proof as the default). Import that file to use the completed theorems.
-/

end Probability
end Exchangeability
